-- Import Jobs table with enum types as text with check constraints
CREATE TABLE IF NOT EXISTS IMPORT_JOBS
(
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    JOB_TYPE            TEXT    NOT NULL CHECK (JOB_TYPE IN ('DATA_IMPORT', 'COVER_EXTRACTION')),
    STATUS              TEXT    NOT NULL CHECK (STATUS IN ('RUNNING', 'COMPLETED', 'FAILED')),
    PROGRESS            TEXT,
    INP_FILES_PROCESSED INTEGER DEFAULT 0,
    BOOKS_ADDED         INTEGER DEFAULT 0,
    BOOKS_UPDATED       INTEGER DEFAULT 0,
    BOOKS_DELETED       INTEGER DEFAULT 0,
    COVERS_ADDED        INTEGER DEFAULT 0,
    BOOK_ERRORS         INTEGER DEFAULT 0,
    COVER_ERRORS        INTEGER DEFAULT 0,
    ERROR_MESSAGE       TEXT,
    STARTED_AT          TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_AT        TEXT,
    CREATED_AT          TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_IMPORT_JOBS_STATUS ON IMPORT_JOBS (STATUS);
CREATE INDEX IF NOT EXISTS IDX_IMPORT_JOBS_TYPE ON IMPORT_JOBS (JOB_TYPE);
CREATE INDEX IF NOT EXISTS IDX_IMPORT_JOBS_STARTED ON IMPORT_JOBS (STARTED_AT DESC);