CREATE TYPE JOB_TYPE_ENUM AS ENUM (
    'DATA_IMPORT',
    'COVER_EXTRACTION'
    );

CREATE TYPE JOB_STATUS_ENUM AS ENUM (
    'RUNNING',
    'COMPLETED',
    'FAILED'
    );

CREATE TABLE IF NOT EXISTS IMPORT_JOBS
(
    ID                  BIGSERIAL PRIMARY KEY,
    JOB_TYPE            JOB_TYPE_ENUM   NOT NULL,
    STATUS              JOB_STATUS_ENUM NOT NULL,
    PROGRESS            TEXT,
    INP_FILES_PROCESSED INTEGER                  DEFAULT 0,
    BOOKS_ADDED         INTEGER                  DEFAULT 0,
    BOOKS_UPDATED       INTEGER                  DEFAULT 0,
    BOOKS_DELETED       INTEGER                  DEFAULT 0,
    COVERS_ADDED        INTEGER                  DEFAULT 0,
    BOOK_ERRORS         INTEGER                  DEFAULT 0,
    COVER_ERRORS        INTEGER                  DEFAULT 0,
    ERROR_MESSAGE       TEXT,
    STARTED_AT          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    COMPLETED_AT        TIMESTAMPTZ,
    CREATED_AT          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS IDX_IMPORT_JOBS_STATUS ON IMPORT_JOBS (STATUS);
CREATE INDEX IF NOT EXISTS IDX_IMPORT_JOBS_TYPE ON IMPORT_JOBS (JOB_TYPE);
CREATE INDEX IF NOT EXISTS IDX_IMPORT_JOBS_STARTED ON IMPORT_JOBS (STARTED_AT DESC);
