-- Kindle Devices Table
CREATE TABLE IF NOT EXISTS KINDLE_DEVICES
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID    INTEGER      NOT NULL,
    EMAIL      TEXT         NOT NULL,
    NAME       TEXT         NOT NULL,
    CREATED_AT TEXT         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TEXT         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, EMAIL)
);

CREATE INDEX IF NOT EXISTS IDX_KINDLE_DEVICES_USER ON KINDLE_DEVICES (USER_ID);
CREATE INDEX IF NOT EXISTS IDX_KINDLE_DEVICES_EMAIL ON KINDLE_DEVICES (EMAIL);

-- Kindle Send Queue Table with enum types as text with check constraints
CREATE TABLE IF NOT EXISTS KINDLE_SEND_QUEUE
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID     INTEGER NOT NULL,
    DEVICE_ID   INTEGER NOT NULL,
    BOOK_ID     INTEGER NOT NULL,
    FORMAT      TEXT    NOT NULL DEFAULT 'EPUB' CHECK (FORMAT IN ('EPUB', 'MOBI')),
    STATUS      TEXT    NOT NULL DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    ATTEMPTS    INTEGER NOT NULL DEFAULT 0,
    NEXT_RUN_AT TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_ERROR  TEXT,
    CREATED_AT  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (DEVICE_ID) REFERENCES KINDLE_DEVICES (ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_QUEUE_STATUS ON KINDLE_SEND_QUEUE (STATUS);
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_QUEUE_NEXT_RUN ON KINDLE_SEND_QUEUE (NEXT_RUN_AT);
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_QUEUE_USER ON KINDLE_SEND_QUEUE (USER_ID);
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_QUEUE_DEVICE ON KINDLE_SEND_QUEUE (DEVICE_ID);
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_QUEUE_BOOK ON KINDLE_SEND_QUEUE (BOOK_ID);

-- Kindle Send Events Table
CREATE TABLE IF NOT EXISTS KINDLE_SEND_EVENTS
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    QUEUE_ID   INTEGER NOT NULL,
    EVENT_TYPE TEXT    NOT NULL,
    DETAILS    TEXT,
    CREATED_AT TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (QUEUE_ID) REFERENCES KINDLE_SEND_QUEUE (ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_EVENTS_QUEUE ON KINDLE_SEND_EVENTS (QUEUE_ID);
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_EVENTS_TYPE ON KINDLE_SEND_EVENTS (EVENT_TYPE);