package migrations

import migrations.model.Migration
import org.intellij.lang.annotations.Language

@Language("SQLite")
private val sql = """
CREATE TABLE IF NOT EXISTS USERS
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    GOOGLE_ID  TEXT UNIQUE      NOT NULL,
    EMAIL      TEXT             NOT NULL,
    NAME       TEXT             NOT NULL,
    AVATAR_URL TEXT,
    STATUS     TEXT             NOT NULL CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED', 'DEACTIVATED')),
    CREATED_AT TEXT             NOT NULL,
    UPDATED_AT TEXT             NOT NULL
);
$next
CREATE TABLE IF NOT EXISTS AUTHORS
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    FULL_NAME  TEXT        NOT NULL
);
$next
CREATE TABLE IF NOT EXISTS SERIES
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME       TEXT        NOT NULL
);
$next
CREATE TABLE IF NOT EXISTS BOOKS
(
    ID            INTEGER PRIMARY KEY,
    TITLE         TEXT        NOT NULL,
    LANGUAGE      TEXT        NOT NULL,
    SERIES_ID     INTEGER,
    SERIES_NUMBER INTEGER,
    FILE_FORMAT   TEXT        NOT NULL,
    FILE_PATH     TEXT        NOT NULL,
    ARCHIVE_PATH  TEXT        NOT NULL,
    FILE_SIZE     INTEGER,
    DATE_ADDED    TEXT        NOT NULL,
    COVER_IMAGE   BLOB,
    CREATED_AT    TEXT        NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);
$next
CREATE TABLE IF NOT EXISTS GENRES
(
    ID   INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT UNIQUE NOT NULL
);
$next
CREATE TABLE IF NOT EXISTS BOOK_AUTHORS
(
    BOOK_ID   INTEGER NOT NULL,
    AUTHOR_ID INTEGER NOT NULL,
    PRIMARY KEY (BOOK_ID, AUTHOR_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID) ON DELETE CASCADE
);
$next
CREATE TABLE IF NOT EXISTS BOOK_GENRES
(
    BOOK_ID  INTEGER NOT NULL,
    GENRE_ID INTEGER NOT NULL,
    PRIMARY KEY (BOOK_ID, GENRE_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) ON DELETE CASCADE
);
$next
CREATE TABLE IF NOT EXISTS BOOK_ENRICHMENT
(
    BOOK_ID     INTEGER PRIMARY KEY,
    ANNOTATION  TEXT,
    EMBEDDING   BLOB,
    STATUS      TEXT NOT NULL CHECK (STATUS IN ('PROCESSING', 'DONE', 'FAILED')),
    ENRICHED_AT TEXT
);
$next
CREATE TABLE IF NOT EXISTS KINDLE_DEVICES
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID    INTEGER      NOT NULL,
    EMAIL      TEXT         NOT NULL,
    NAME       TEXT         NOT NULL,
    CREATED_AT TEXT         NOT NULL,
    UPDATED_AT TEXT         NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, EMAIL)
);
$next
CREATE TABLE IF NOT EXISTS KINDLE_SEND_QUEUE
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID     INTEGER NOT NULL,
    DEVICE_ID   INTEGER NOT NULL,
    BOOK_ID     INTEGER NOT NULL,
    BOOK_TITLE  TEXT    NOT NULL,
    FORMAT      TEXT    NOT NULL CHECK (FORMAT IN ('EPUB')),
    STATUS      TEXT    NOT NULL CHECK (STATUS IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    ATTEMPTS    INTEGER NOT NULL,
    NEXT_RUN_AT TEXT    NOT NULL,
    LAST_ERROR  TEXT,
    CREATED_AT  TEXT    NOT NULL,
    UPDATED_AT  TEXT    NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (DEVICE_ID) REFERENCES KINDLE_DEVICES (ID) ON DELETE CASCADE
);
$next
CREATE TABLE IF NOT EXISTS KINDLE_SEND_EVENTS
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    QUEUE_ID   INTEGER NOT NULL,
    EVENT_TYPE TEXT    NOT NULL,
    DETAILS    TEXT,
    CREATED_AT TEXT    NOT NULL,
    FOREIGN KEY (QUEUE_ID) REFERENCES KINDLE_SEND_QUEUE (ID) ON DELETE CASCADE
);
$next
CREATE INDEX IF NOT EXISTS IDX_BOOKS_TITLE ON BOOKS (TITLE);
$next
CREATE INDEX IF NOT EXISTS IDX_BOOKS_LANGUAGE ON BOOKS (LANGUAGE);
$next
CREATE INDEX IF NOT EXISTS IDX_BOOKS_SERIES ON BOOKS (SERIES_ID);
$next
CREATE INDEX IF NOT EXISTS IDX_AUTHORS_NAME ON AUTHORS (FULL_NAME);
$next
CREATE INDEX IF NOT EXISTS IDX_BOOK_AUTHORS_BOOK ON BOOK_AUTHORS (BOOK_ID);
$next
CREATE INDEX IF NOT EXISTS IDX_BOOK_AUTHORS_AUTHOR ON BOOK_AUTHORS (AUTHOR_ID);
$next
CREATE INDEX IF NOT EXISTS IDX_BOOK_GENRES_BOOK ON BOOK_GENRES (BOOK_ID);
$next
CREATE INDEX IF NOT EXISTS IDX_BOOK_GENRES_GENRE ON BOOK_GENRES (GENRE_ID);
$next
CREATE INDEX IF NOT EXISTS IDX_GENRES_NAME ON GENRES (NAME);
$next
CREATE INDEX IF NOT EXISTS IDX_BOOK_ENRICHMENT_STATUS ON BOOK_ENRICHMENT (STATUS);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_DEVICES_USER ON KINDLE_DEVICES (USER_ID);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_DEVICES_EMAIL ON KINDLE_DEVICES (EMAIL);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_QUEUE_STATUS ON KINDLE_SEND_QUEUE (STATUS);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_QUEUE_NEXT_RUN ON KINDLE_SEND_QUEUE (NEXT_RUN_AT);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_QUEUE_USER ON KINDLE_SEND_QUEUE (USER_ID);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_QUEUE_DEVICE ON KINDLE_SEND_QUEUE (DEVICE_ID);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_QUEUE_BOOK ON KINDLE_SEND_QUEUE (BOOK_ID);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_EVENTS_QUEUE ON KINDLE_SEND_EVENTS (QUEUE_ID);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_SEND_EVENTS_TYPE ON KINDLE_SEND_EVENTS (EVENT_TYPE);
""".trimIndent()

val v1: Migration
    get() = Migration(
        version = 1,
        script = sql,
    )
