package migrations

import migrations.model.Migration
import org.intellij.lang.annotations.Language

@Language("SQLite")
private val sql = """
CREATE TABLE IF NOT EXISTS KINDLE_UPLOAD_QUEUE
(
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID       INTEGER NOT NULL,
    DEVICE_ID     INTEGER NOT NULL,
    FILE_NAME     TEXT    NOT NULL,
    STORED_PATH   TEXT,
    SIZE_BYTES    INTEGER NOT NULL,
    SOURCE_FORMAT TEXT    NOT NULL CHECK (SOURCE_FORMAT IN ('EPUB', 'PDF', 'FB2')),
    SEND_FORMAT   TEXT    NOT NULL CHECK (SEND_FORMAT IN ('EPUB', 'PDF')),
    STATUS        TEXT    NOT NULL CHECK (STATUS IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    ATTEMPTS      INTEGER NOT NULL,
    NEXT_RUN_AT   TEXT    NOT NULL,
    LAST_ERROR    TEXT,
    CREATED_AT    TEXT    NOT NULL,
    UPDATED_AT    TEXT    NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (DEVICE_ID) REFERENCES KINDLE_DEVICES (ID) ON DELETE CASCADE
);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_UPLOAD_QUEUE_STATUS ON KINDLE_UPLOAD_QUEUE (STATUS);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_UPLOAD_QUEUE_NEXT_RUN ON KINDLE_UPLOAD_QUEUE (NEXT_RUN_AT);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_UPLOAD_QUEUE_USER ON KINDLE_UPLOAD_QUEUE (USER_ID);
$next
CREATE INDEX IF NOT EXISTS IDX_KINDLE_UPLOAD_QUEUE_DEVICE ON KINDLE_UPLOAD_QUEUE (DEVICE_ID);
""".trimIndent()

val v3: Migration
    get() = Migration(
        version = 3,
        script = sql,
    )
