# docker compose -f docker-compose.dev.yml up -d
name: "kotbusta"

services:
  database:
    image: "postgres:17.5"
    container_name: "database"
    restart: "always"
    mem_limit: "128m"
    memswap_limit: "0m"
    environment:
      POSTGRES_PASSWORD: "kotbusta"
      POSTGRES_USER: "kotbusta"
      POSTGRES_DB: "kotbusta"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:9578:5432"
volumes:
  pgdata:
