version: '3.8'

services:
  kotbusta-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./books-data:/app/books-data:ro
    environment:
      - DATABASE_PATH=/app/data/kotbusta.db
      - BOOKS_DATA_PATH=/app/books-data
      - CONVERSION_SERVICE_URL=http://conversion-service:8081
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - conversion-service
    restart: unless-stopped

volumes:
  kotbusta-data:
    driver: local
