/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.enums


import io.heapy.kotbusta.jooq.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class UserStatusEnum(@get:JvmName("literal") public val literal: String) : EnumType {
    PENDING("PENDING"),
    APPROVED("APPROVED"),
    REJECTED("REJECTED"),
    DEACTIVATED("DEACTIVATED");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "user_status_enum"
    override fun getLiteral(): String = literal
}
