/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.BookGenres

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class BookGenresRecord private constructor() : UpdatableRecordImpl<BookGenresRecord>(BookGenres.BOOK_GENRES) {

    open var bookId: Int
        set(value): Unit = set(0, value)
        get(): Int = get(0) as Int

    open var genreId: Int
        set(value): Unit = set(1, value)
        get(): Int = get(1) as Int

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Int?, Int?> = super.key() as Record2<Int?, Int?>

    /**
     * Create a detached, initialised BookGenresRecord
     */
    constructor(bookId: Int, genreId: Int): this() {
        this.bookId = bookId
        this.genreId = genreId
        resetTouchedOnNotNull()
    }
}
