/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.BookAuthors

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class BookAuthorsRecord private constructor() : UpdatableRecordImpl<BookAuthorsRecord>(BookAuthors.BOOK_AUTHORS) {

    open var bookId: Int
        set(value): Unit = set(0, value)
        get(): Int = get(0) as Int

    open var authorId: Int
        set(value): Unit = set(1, value)
        get(): Int = get(1) as Int

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Int?, Int?> = super.key() as Record2<Int?, Int?>

    /**
     * Create a detached, initialised BookAuthorsRecord
     */
    constructor(bookId: Int, authorId: Int): this() {
        this.bookId = bookId
        this.authorId = authorId
        resetTouchedOnNotNull()
    }
}
