/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.BookEnrichment

import kotlin.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class BookEnrichmentRecord private constructor() : UpdatableRecordImpl<BookEnrichmentRecord>(BookEnrichment.BOOK_ENRICHMENT) {

    open var bookId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var `annotation`: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var embedding: ByteArray?
        set(value): Unit = set(2, value)
        get(): ByteArray? = get(2) as ByteArray?

    open var status: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var enrichedAt: Instant?
        set(value): Unit = set(4, value)
        get(): Instant? = get(4) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised BookEnrichmentRecord
     */
    constructor(bookId: Int? = null, `annotation`: String? = null, embedding: ByteArray? = null, status: String, enrichedAt: Instant? = null): this() {
        this.bookId = bookId
        this.`annotation` = `annotation`
        this.embedding = embedding
        this.status = status
        this.enrichedAt = enrichedAt
        resetTouchedOnNotNull()
    }
}
