/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.Downloads
import io.heapy.kotbusta.jooq.tables.interfaces.IDownloads

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DownloadsRecord private constructor() : UpdatableRecordImpl<DownloadsRecord>(Downloads.DOWNLOADS), IDownloads {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var userId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var bookId: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open override var format: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open override var createdAt: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IDownloads) {
        this.id = from.id
        this.userId = from.userId
        this.bookId = from.bookId
        this.format = from.format
        this.createdAt = from.createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised DownloadsRecord
     */
    constructor(id: Long? = null, userId: Long, bookId: Long, format: String, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.userId = userId
        this.bookId = bookId
        this.format = format
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised DownloadsRecord
     */
    constructor(value: IDownloads?): this() {
        if (value != null) {
            this.id = value.id
            this.userId = value.userId
            this.bookId = value.bookId
            this.format = value.format
            this.createdAt = value.createdAt
            resetTouchedOnNotNull()
        }
    }
}
