/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.FeaturedBooks

import kotlin.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class FeaturedBooksRecord private constructor() : UpdatableRecordImpl<FeaturedBooksRecord>(FeaturedBooks.FEATURED_BOOKS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var bookId: Int
        set(value): Unit = set(1, value)
        get(): Int = get(1) as Int

    open var source: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var externalTitle: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var externalAuthor: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open var rating: Float
        set(value): Unit = set(5, value)
        get(): Float = get(5) as Float

    open var sourceRank: Int
        set(value): Unit = set(6, value)
        get(): Int = get(6) as Int

    open var fetchedAt: Instant
        set(value): Unit = set(7, value)
        get(): Instant = get(7) as Instant

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised FeaturedBooksRecord
     */
    constructor(id: Int? = null, bookId: Int, source: String, externalTitle: String, externalAuthor: String, rating: Float, sourceRank: Int, fetchedAt: Instant): this() {
        this.id = id
        this.bookId = bookId
        this.source = source
        this.externalTitle = externalTitle
        this.externalAuthor = externalAuthor
        this.rating = rating
        this.sourceRank = sourceRank
        this.fetchedAt = fetchedAt
        resetTouchedOnNotNull()
    }
}
