/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.KindleUploadQueue

import kotlin.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class KindleUploadQueueRecord private constructor() : UpdatableRecordImpl<KindleUploadQueueRecord>(KindleUploadQueue.KINDLE_UPLOAD_QUEUE) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int
        set(value): Unit = set(1, value)
        get(): Int = get(1) as Int

    open var deviceId: Int
        set(value): Unit = set(2, value)
        get(): Int = get(2) as Int

    open var fileName: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var storedPath: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var sizeBytes: Int
        set(value): Unit = set(5, value)
        get(): Int = get(5) as Int

    open var sourceFormat: String
        set(value): Unit = set(6, value)
        get(): String = get(6) as String

    open var sendFormat: String
        set(value): Unit = set(7, value)
        get(): String = get(7) as String

    open var status: String
        set(value): Unit = set(8, value)
        get(): String = get(8) as String

    open var attempts: Int
        set(value): Unit = set(9, value)
        get(): Int = get(9) as Int

    open var nextRunAt: Instant
        set(value): Unit = set(10, value)
        get(): Instant = get(10) as Instant

    open var lastError: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var createdAt: Instant
        set(value): Unit = set(12, value)
        get(): Instant = get(12) as Instant

    open var updatedAt: Instant
        set(value): Unit = set(13, value)
        get(): Instant = get(13) as Instant

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised KindleUploadQueueRecord
     */
    constructor(id: Int? = null, userId: Int, deviceId: Int, fileName: String, storedPath: String? = null, sizeBytes: Int, sourceFormat: String, sendFormat: String, status: String, attempts: Int, nextRunAt: Instant, lastError: String? = null, createdAt: Instant, updatedAt: Instant): this() {
        this.id = id
        this.userId = userId
        this.deviceId = deviceId
        this.fileName = fileName
        this.storedPath = storedPath
        this.sizeBytes = sizeBytes
        this.sourceFormat = sourceFormat
        this.sendFormat = sendFormat
        this.status = status
        this.attempts = attempts
        this.nextRunAt = nextRunAt
        this.lastError = lastError
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
