/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.KindleDevices

import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class KindleDevicesRecord private constructor() : UpdatableRecordImpl<KindleDevicesRecord>(KindleDevices.KINDLE_DEVICES) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int
        set(value): Unit = set(1, value)
        get(): Int = get(1) as Int

    open var email: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var name: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var createdAt: Instant
        set(value): Unit = set(4, value)
        get(): Instant = get(4) as Instant

    open var updatedAt: Instant
        set(value): Unit = set(5, value)
        get(): Instant = get(5) as Instant

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised KindleDevicesRecord
     */
    constructor(id: Int? = null, userId: Int, email: String, name: String, createdAt: Instant, updatedAt: Instant): this() {
        this.id = id
        this.userId = userId
        this.email = email
        this.name = name
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
