/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.KindleSendEvents

import kotlin.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class KindleSendEventsRecord private constructor() : UpdatableRecordImpl<KindleSendEventsRecord>(KindleSendEvents.KINDLE_SEND_EVENTS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var queueId: Int
        set(value): Unit = set(1, value)
        get(): Int = get(1) as Int

    open var eventType: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var details: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var createdAt: Instant
        set(value): Unit = set(4, value)
        get(): Instant = get(4) as Instant

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised KindleSendEventsRecord
     */
    constructor(id: Int? = null, queueId: Int, eventType: String, details: String? = null, createdAt: Instant): this() {
        this.id = id
        this.queueId = queueId
        this.eventType = eventType
        this.details = details
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }
}
