/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.Series

import kotlin.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class SeriesRecord private constructor() : UpdatableRecordImpl<SeriesRecord>(Series.SERIES) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var createdAt: Instant
        set(value): Unit = set(2, value)
        get(): Instant = get(2) as Instant

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised SeriesRecord
     */
    constructor(id: Int? = null, name: String, createdAt: Instant): this() {
        this.id = id
        this.name = name
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }
}
