/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.Series
import io.heapy.kotbusta.jooq.tables.interfaces.ISeries

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class SeriesRecord private constructor() : UpdatableRecordImpl<SeriesRecord>(Series.SERIES), ISeries {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open override var createdAt: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: ISeries) {
        this.id = from.id
        this.name = from.name
        this.createdAt = from.createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised SeriesRecord
     */
    constructor(id: Long? = null, name: String, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.name = name
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised SeriesRecord
     */
    constructor(value: ISeries?): this() {
        if (value != null) {
            this.id = value.id
            this.name = value.name
            this.createdAt = value.createdAt
            resetTouchedOnNotNull()
        }
    }
}
