/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.UserNotes
import io.heapy.kotbusta.jooq.tables.interfaces.IUserNotes

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UserNotesRecord private constructor() : UpdatableRecordImpl<UserNotesRecord>(UserNotes.USER_NOTES), IUserNotes {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var userId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var bookId: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open override var note: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsPrivate")
    open override var isPrivate: Boolean?
        set(value): Unit = set(4, value)
        get(): Boolean? = get(4) as Boolean?

    open override var createdAt: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open override var updatedAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IUserNotes) {
        this.id = from.id
        this.userId = from.userId
        this.bookId = from.bookId
        this.note = from.note
        this.isPrivate = from.isPrivate
        this.createdAt = from.createdAt
        this.updatedAt = from.updatedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised UserNotesRecord
     */
    constructor(id: Long? = null, userId: Long, bookId: Long, note: String, isPrivate: Boolean? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.userId = userId
        this.bookId = bookId
        this.note = note
        this.isPrivate = isPrivate
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised UserNotesRecord
     */
    constructor(value: IUserNotes?): this() {
        if (value != null) {
            this.id = value.id
            this.userId = value.userId
            this.bookId = value.bookId
            this.note = value.note
            this.isPrivate = value.isPrivate
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            resetTouchedOnNotNull()
        }
    }
}
