/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.Users

import kotlin.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UsersRecord private constructor() : UpdatableRecordImpl<UsersRecord>(Users.USERS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var googleId: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var email: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var name: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var avatarUrl: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var status: String
        set(value): Unit = set(5, value)
        get(): String = get(5) as String

    open var createdAt: Instant
        set(value): Unit = set(6, value)
        get(): Instant = get(6) as Instant

    open var updatedAt: Instant
        set(value): Unit = set(7, value)
        get(): Instant = get(7) as Instant

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(id: Int? = null, googleId: String, email: String, name: String, avatarUrl: String? = null, status: String, createdAt: Instant, updatedAt: Instant): this() {
        this.id = id
        this.googleId = googleId
        this.email = email
        this.name = name
        this.avatarUrl = avatarUrl
        this.status = status
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
