/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.UserStars

import java.time.Instant

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UserStarsRecord private constructor() : UpdatableRecordImpl<UserStarsRecord>(UserStars.USER_STARS) {

    open var userId: Int
        set(value): Unit = set(0, value)
        get(): Int = get(0) as Int

    open var bookId: Int
        set(value): Unit = set(1, value)
        get(): Int = get(1) as Int

    open var createdAt: Instant
        set(value): Unit = set(2, value)
        get(): Instant = get(2) as Instant

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Int?, Int?> = super.key() as Record2<Int?, Int?>

    /**
     * Create a detached, initialised UserStarsRecord
     */
    constructor(userId: Int, bookId: Int, createdAt: Instant): this() {
        this.userId = userId
        this.bookId = bookId
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }
}
