/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.UserStars

import java.time.OffsetDateTime

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UserStarsRecord private constructor() : UpdatableRecordImpl<UserStarsRecord>(UserStars.USER_STARS) {

    open var userId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open var bookId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    /**
     * Create a detached, initialised UserStarsRecord
     */
    constructor(userId: Long, bookId: Long, createdAt: OffsetDateTime? = null): this() {
        this.userId = userId
        this.bookId = bookId
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }
}
