/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.Users
import io.heapy.kotbusta.jooq.tables.interfaces.IUsers

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UsersRecord private constructor() : UpdatableRecordImpl<UsersRecord>(Users.USERS), IUsers {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var googleId: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open override var email: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open override var name: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open override var avatarUrl: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open override var createdAt: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open override var updatedAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IUsers) {
        this.id = from.id
        this.googleId = from.googleId
        this.email = from.email
        this.name = from.name
        this.avatarUrl = from.avatarUrl
        this.createdAt = from.createdAt
        this.updatedAt = from.updatedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(id: Long? = null, googleId: String, email: String, name: String, avatarUrl: String? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.googleId = googleId
        this.email = email
        this.name = name
        this.avatarUrl = avatarUrl
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(value: IUsers?): this() {
        if (value != null) {
            this.id = value.id
            this.googleId = value.googleId
            this.email = value.email
            this.name = value.name
            this.avatarUrl = value.avatarUrl
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            resetTouchedOnNotNull()
        }
    }
}
