/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.enums.UserStatusEnum
import io.heapy.kotbusta.jooq.tables.Users

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UsersRecord private constructor() : UpdatableRecordImpl<UsersRecord>(Users.USERS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var googleId: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var email: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var name: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var avatarUrl: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var status: UserStatusEnum?
        set(value): Unit = set(5, value)
        get(): UserStatusEnum? = get(5) as UserStatusEnum?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(id: Long? = null, googleId: String, email: String, name: String, avatarUrl: String? = null, status: UserStatusEnum? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.googleId = googleId
        this.email = email
        this.name = name
        this.avatarUrl = avatarUrl
        this.status = status
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
