/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.records


import io.heapy.kotbusta.jooq.tables.UserStars
import io.heapy.kotbusta.jooq.tables.interfaces.IUserStars

import java.time.OffsetDateTime

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UserStarsRecord private constructor() : UpdatableRecordImpl<UserStarsRecord>(UserStars.USER_STARS), IUserStars {

    open override var userId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open override var bookId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var createdAt: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IUserStars) {
        this.userId = from.userId
        this.bookId = from.bookId
        this.createdAt = from.createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised UserStarsRecord
     */
    constructor(userId: Long, bookId: Long, createdAt: OffsetDateTime? = null): this() {
        this.userId = userId
        this.bookId = bookId
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised UserStarsRecord
     */
    constructor(value: IUserStars?): this() {
        if (value != null) {
            this.userId = value.userId
            this.bookId = value.bookId
            this.createdAt = value.createdAt
            resetTouchedOnNotNull()
        }
    }
}
