/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.DefaultSchema
import io.heapy.kotbusta.jooq.KotlinInstantConverter
import io.heapy.kotbusta.jooq.indexes.IDX_BOOK_ENRICHMENT_STATUS
import io.heapy.kotbusta.jooq.keys.BOOK_ENRICHMENT__PK_BOOK_ENRICHMENT
import io.heapy.kotbusta.jooq.tables.records.BookEnrichmentRecord

import kotlin.collections.Collection
import kotlin.collections.List
import kotlin.time.Instant

import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class BookEnrichment(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BookEnrichmentRecord>?,
    parentPath: InverseForeignKey<out Record, BookEnrichmentRecord>?,
    aliased: Table<BookEnrichmentRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BookEnrichmentRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>BOOK_ENRICHMENT</code>
         */
        val BOOK_ENRICHMENT: BookEnrichment = BookEnrichment()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BookEnrichmentRecord> = BookEnrichmentRecord::class.java

    /**
     * The column <code>BOOK_ENRICHMENT.BOOK_ID</code>.
     */
    val BOOK_ID: TableField<BookEnrichmentRecord, Int?> = createField(DSL.name("BOOK_ID"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>BOOK_ENRICHMENT.ANNOTATION</code>.
     */
    val ANNOTATION: TableField<BookEnrichmentRecord, String?> = createField(DSL.name("ANNOTATION"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>BOOK_ENRICHMENT.EMBEDDING</code>.
     */
    val EMBEDDING: TableField<BookEnrichmentRecord, ByteArray?> = createField(DSL.name("EMBEDDING"), SQLDataType.BLOB, this, "")

    /**
     * The column <code>BOOK_ENRICHMENT.STATUS</code>.
     */
    val STATUS: TableField<BookEnrichmentRecord, String?> = createField(DSL.name("STATUS"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>BOOK_ENRICHMENT.ENRICHED_AT</code>.
     */
    val ENRICHED_AT: TableField<BookEnrichmentRecord, Instant?> = createField(DSL.name("ENRICHED_AT"), SQLDataType.CLOB, this, "", KotlinInstantConverter())

    private constructor(alias: Name, aliased: Table<BookEnrichmentRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BookEnrichmentRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BookEnrichmentRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>BOOK_ENRICHMENT</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>BOOK_ENRICHMENT</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>BOOK_ENRICHMENT</code> table reference
     */
    constructor(): this(DSL.name("BOOK_ENRICHMENT"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_BOOK_ENRICHMENT_STATUS)
    override fun getPrimaryKey(): UniqueKey<BookEnrichmentRecord> = BOOK_ENRICHMENT__PK_BOOK_ENRICHMENT
    override fun getChecks(): List<Check<BookEnrichmentRecord>> = listOf(
        Internal.createCheck(this, DSL.name(""), "STATUS in ('PROCESSING', 'DONE', 'FAILED')", true)
    )
    override fun `as`(alias: String): BookEnrichment = BookEnrichment(DSL.name(alias), this)
    override fun `as`(alias: Name): BookEnrichment = BookEnrichment(alias, this)
    override fun `as`(alias: Table<*>): BookEnrichment = BookEnrichment(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BookEnrichment = BookEnrichment(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BookEnrichment = BookEnrichment(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BookEnrichment = BookEnrichment(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): BookEnrichment = BookEnrichment(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): BookEnrichment = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): BookEnrichment = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): BookEnrichment = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): BookEnrichment = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): BookEnrichment = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): BookEnrichment = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): BookEnrichment = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): BookEnrichment = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): BookEnrichment = where(DSL.notExists(select))
}
