/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.DefaultSchema
import io.heapy.kotbusta.jooq.indexes.IDX_BOOK_GENRES_BOOK
import io.heapy.kotbusta.jooq.indexes.IDX_BOOK_GENRES_GENRE
import io.heapy.kotbusta.jooq.keys.BOOK_GENRES__FK_BOOK_GENRES_PK_BOOKS
import io.heapy.kotbusta.jooq.keys.BOOK_GENRES__FK_BOOK_GENRES_PK_GENRES
import io.heapy.kotbusta.jooq.keys.BOOK_GENRES__PK_BOOK_GENRES
import io.heapy.kotbusta.jooq.tables.Books.BooksPath
import io.heapy.kotbusta.jooq.tables.Genres.GenresPath
import io.heapy.kotbusta.jooq.tables.records.BookGenresRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class BookGenres(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BookGenresRecord>?,
    parentPath: InverseForeignKey<out Record, BookGenresRecord>?,
    aliased: Table<BookGenresRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BookGenresRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>BOOK_GENRES</code>
         */
        val BOOK_GENRES: BookGenres = BookGenres()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BookGenresRecord> = BookGenresRecord::class.java

    /**
     * The column <code>BOOK_GENRES.BOOK_ID</code>.
     */
    val BOOK_ID: TableField<BookGenresRecord, Int?> = createField(DSL.name("BOOK_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>BOOK_GENRES.GENRE_ID</code>.
     */
    val GENRE_ID: TableField<BookGenresRecord, Int?> = createField(DSL.name("GENRE_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<BookGenresRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BookGenresRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BookGenresRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>BOOK_GENRES</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>BOOK_GENRES</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>BOOK_GENRES</code> table reference
     */
    constructor(): this(DSL.name("BOOK_GENRES"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BookGenresRecord>?, parentPath: InverseForeignKey<out Record, BookGenresRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, BOOK_GENRES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class BookGenresPath : BookGenres, Path<BookGenresRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BookGenresRecord>?, parentPath: InverseForeignKey<out Record, BookGenresRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<BookGenresRecord>): super(alias, aliased)
        override fun `as`(alias: String): BookGenresPath = BookGenresPath(DSL.name(alias), this)
        override fun `as`(alias: Name): BookGenresPath = BookGenresPath(alias, this)
        override fun `as`(alias: Table<*>): BookGenresPath = BookGenresPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_BOOK_GENRES_BOOK, IDX_BOOK_GENRES_GENRE)
    override fun getPrimaryKey(): UniqueKey<BookGenresRecord> = BOOK_GENRES__PK_BOOK_GENRES
    override fun getReferences(): List<ForeignKey<BookGenresRecord, *>> = listOf(BOOK_GENRES__FK_BOOK_GENRES_PK_BOOKS, BOOK_GENRES__FK_BOOK_GENRES_PK_GENRES)

    /**
     * Get the implicit join path to the <code>BOOKS</code> table.
     */
    fun books(): BooksPath = books
    val books: BooksPath by lazy { BooksPath(this, BOOK_GENRES__FK_BOOK_GENRES_PK_BOOKS, null) }

    /**
     * Get the implicit join path to the <code>GENRES</code> table.
     */
    fun genres(): GenresPath = genres
    val genres: GenresPath by lazy { GenresPath(this, BOOK_GENRES__FK_BOOK_GENRES_PK_GENRES, null) }
    override fun `as`(alias: String): BookGenres = BookGenres(DSL.name(alias), this)
    override fun `as`(alias: Name): BookGenres = BookGenres(alias, this)
    override fun `as`(alias: Table<*>): BookGenres = BookGenres(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BookGenres = BookGenres(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BookGenres = BookGenres(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BookGenres = BookGenres(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): BookGenres = BookGenres(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): BookGenres = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): BookGenres = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): BookGenres = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): BookGenres = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): BookGenres = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): BookGenres = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): BookGenres = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): BookGenres = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): BookGenres = where(DSL.notExists(select))
}
