/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.Public
import io.heapy.kotbusta.jooq.indexes.IDX_BOOKS_GENRE
import io.heapy.kotbusta.jooq.indexes.IDX_BOOKS_LANGUAGE
import io.heapy.kotbusta.jooq.indexes.IDX_BOOKS_SERIES
import io.heapy.kotbusta.jooq.indexes.IDX_BOOKS_TITLE
import io.heapy.kotbusta.jooq.keys.BOOKS_PKEY
import io.heapy.kotbusta.jooq.keys.BOOKS__FK_BOOKS_SERIES
import io.heapy.kotbusta.jooq.keys.BOOK_AUTHORS__FK_BOOK_AUTHORS_BOOK
import io.heapy.kotbusta.jooq.keys.DOWNLOADS__FK_DOWNLOADS_BOOK
import io.heapy.kotbusta.jooq.keys.USER_COMMENTS__FK_USER_COMMENTS_BOOK
import io.heapy.kotbusta.jooq.keys.USER_NOTES__FK_USER_NOTES_BOOK
import io.heapy.kotbusta.jooq.keys.USER_STARS__FK_USER_STARS_BOOK
import io.heapy.kotbusta.jooq.tables.Authors.AuthorsPath
import io.heapy.kotbusta.jooq.tables.BookAuthors.BookAuthorsPath
import io.heapy.kotbusta.jooq.tables.Downloads.DownloadsPath
import io.heapy.kotbusta.jooq.tables.Series.SeriesPath
import io.heapy.kotbusta.jooq.tables.UserComments.UserCommentsPath
import io.heapy.kotbusta.jooq.tables.UserNotes.UserNotesPath
import io.heapy.kotbusta.jooq.tables.UserStars.UserStarsPath
import io.heapy.kotbusta.jooq.tables.Users.UsersPath
import io.heapy.kotbusta.jooq.tables.records.BooksRecord

import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Books(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BooksRecord>?,
    parentPath: InverseForeignKey<out Record, BooksRecord>?,
    aliased: Table<BooksRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BooksRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.books</code>
         */
        val BOOKS: Books = Books()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BooksRecord> = BooksRecord::class.java

    /**
     * The column <code>public.books.id</code>.
     */
    val ID: TableField<BooksRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.books.title</code>.
     */
    val TITLE: TableField<BooksRecord, String?> = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.books.annotation</code>.
     */
    val ANNOTATION: TableField<BooksRecord, String?> = createField(DSL.name("annotation"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.books.genre</code>.
     */
    val GENRE: TableField<BooksRecord, String?> = createField(DSL.name("genre"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.books.language</code>.
     */
    val LANGUAGE: TableField<BooksRecord, String?> = createField(DSL.name("language"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'ru'::text"), SQLDataType.CLOB)), this, "")

    /**
     * The column <code>public.books.series_id</code>.
     */
    val SERIES_ID: TableField<BooksRecord, Long?> = createField(DSL.name("series_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.books.series_number</code>.
     */
    val SERIES_NUMBER: TableField<BooksRecord, Int?> = createField(DSL.name("series_number"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.books.file_path</code>.
     */
    val FILE_PATH: TableField<BooksRecord, String?> = createField(DSL.name("file_path"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.books.archive_path</code>.
     */
    val ARCHIVE_PATH: TableField<BooksRecord, String?> = createField(DSL.name("archive_path"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.books.file_size</code>.
     */
    val FILE_SIZE: TableField<BooksRecord, Long?> = createField(DSL.name("file_size"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.books.date_added</code>.
     */
    val DATE_ADDED: TableField<BooksRecord, OffsetDateTime?> = createField(DSL.name("date_added"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.books.cover_image</code>.
     */
    val COVER_IMAGE: TableField<BooksRecord, ByteArray?> = createField(DSL.name("cover_image"), SQLDataType.BLOB, this, "")

    /**
     * The column <code>public.books.created_at</code>.
     */
    val CREATED_AT: TableField<BooksRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<BooksRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BooksRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BooksRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.books</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.books</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.books</code> table reference
     */
    constructor(): this(DSL.name("books"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BooksRecord>?, parentPath: InverseForeignKey<out Record, BooksRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, BOOKS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class BooksPath : Books, Path<BooksRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BooksRecord>?, parentPath: InverseForeignKey<out Record, BooksRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<BooksRecord>): super(alias, aliased)
        override fun `as`(alias: String): BooksPath = BooksPath(DSL.name(alias), this)
        override fun `as`(alias: Name): BooksPath = BooksPath(alias, this)
        override fun `as`(alias: Table<*>): BooksPath = BooksPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_BOOKS_GENRE, IDX_BOOKS_LANGUAGE, IDX_BOOKS_SERIES, IDX_BOOKS_TITLE)
    override fun getPrimaryKey(): UniqueKey<BooksRecord> = BOOKS_PKEY
    override fun getReferences(): List<ForeignKey<BooksRecord, *>> = listOf(BOOKS__FK_BOOKS_SERIES)

    /**
     * Get the implicit join path to the <code>public.series</code> table.
     */
    fun series(): SeriesPath = series
    val series: SeriesPath by lazy { SeriesPath(this, BOOKS__FK_BOOKS_SERIES, null) }

    private lateinit var _bookAuthors: BookAuthorsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.book_authors</code> table
     */
    fun bookAuthors(): BookAuthorsPath {
        if (!this::_bookAuthors.isInitialized)
            _bookAuthors = BookAuthorsPath(this, null, BOOK_AUTHORS__FK_BOOK_AUTHORS_BOOK.inverseKey)

        return _bookAuthors;
    }

    val bookAuthors: BookAuthorsPath
        get(): BookAuthorsPath = bookAuthors()

    private lateinit var _downloads: DownloadsPath

    /**
     * Get the implicit to-many join path to the <code>public.downloads</code>
     * table
     */
    fun downloads(): DownloadsPath {
        if (!this::_downloads.isInitialized)
            _downloads = DownloadsPath(this, null, DOWNLOADS__FK_DOWNLOADS_BOOK.inverseKey)

        return _downloads;
    }

    val downloads: DownloadsPath
        get(): DownloadsPath = downloads()

    private lateinit var _userComments: UserCommentsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.user_comments</code> table
     */
    fun userComments(): UserCommentsPath {
        if (!this::_userComments.isInitialized)
            _userComments = UserCommentsPath(this, null, USER_COMMENTS__FK_USER_COMMENTS_BOOK.inverseKey)

        return _userComments;
    }

    val userComments: UserCommentsPath
        get(): UserCommentsPath = userComments()

    private lateinit var _userNotes: UserNotesPath

    /**
     * Get the implicit to-many join path to the <code>public.user_notes</code>
     * table
     */
    fun userNotes(): UserNotesPath {
        if (!this::_userNotes.isInitialized)
            _userNotes = UserNotesPath(this, null, USER_NOTES__FK_USER_NOTES_BOOK.inverseKey)

        return _userNotes;
    }

    val userNotes: UserNotesPath
        get(): UserNotesPath = userNotes()

    private lateinit var _userStars: UserStarsPath

    /**
     * Get the implicit to-many join path to the <code>public.user_stars</code>
     * table
     */
    fun userStars(): UserStarsPath {
        if (!this::_userStars.isInitialized)
            _userStars = UserStarsPath(this, null, USER_STARS__FK_USER_STARS_BOOK.inverseKey)

        return _userStars;
    }

    val userStars: UserStarsPath
        get(): UserStarsPath = userStars()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.authors</code> table
     */
    val authors: AuthorsPath
        get(): AuthorsPath = bookAuthors().authors()

    /**
     * Get the implicit many-to-many join path to the <code>public.users</code>
     * table
     */
    val users: UsersPath
        get(): UsersPath = userStars().users()
    override fun `as`(alias: String): Books = Books(DSL.name(alias), this)
    override fun `as`(alias: Name): Books = Books(alias, this)
    override fun `as`(alias: Table<*>): Books = Books(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Books = Books(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Books = Books(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Books = Books(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Books = Books(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Books = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Books = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Books = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Books = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Books = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Books = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Books = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Books = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Books = where(DSL.notExists(select))
}
