/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.DefaultSchema
import io.heapy.kotbusta.jooq.KotlinInstantConverter
import io.heapy.kotbusta.jooq.indexes.IDX_FEATURED_BOOKS_RATING
import io.heapy.kotbusta.jooq.indexes.IDX_FEATURED_BOOKS_SOURCE_BOOK
import io.heapy.kotbusta.jooq.keys.FEATURED_BOOKS__FK_FEATURED_BOOKS_PK_BOOKS
import io.heapy.kotbusta.jooq.keys.FEATURED_BOOKS__PK_FEATURED_BOOKS
import io.heapy.kotbusta.jooq.tables.Books.BooksPath
import io.heapy.kotbusta.jooq.tables.records.FeaturedBooksRecord

import kotlin.collections.Collection
import kotlin.collections.List
import kotlin.time.Instant

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class FeaturedBooks(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, FeaturedBooksRecord>?,
    parentPath: InverseForeignKey<out Record, FeaturedBooksRecord>?,
    aliased: Table<FeaturedBooksRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<FeaturedBooksRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>FEATURED_BOOKS</code>
         */
        val FEATURED_BOOKS: FeaturedBooks = FeaturedBooks()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<FeaturedBooksRecord> = FeaturedBooksRecord::class.java

    /**
     * The column <code>FEATURED_BOOKS.ID</code>.
     */
    val ID: TableField<FeaturedBooksRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.generatedByDefaultAsIdentity(), this, "")

    /**
     * The column <code>FEATURED_BOOKS.BOOK_ID</code>.
     */
    val BOOK_ID: TableField<FeaturedBooksRecord, Int?> = createField(DSL.name("BOOK_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>FEATURED_BOOKS.SOURCE</code>.
     */
    val SOURCE: TableField<FeaturedBooksRecord, String?> = createField(DSL.name("SOURCE"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>FEATURED_BOOKS.EXTERNAL_TITLE</code>.
     */
    val EXTERNAL_TITLE: TableField<FeaturedBooksRecord, String?> = createField(DSL.name("EXTERNAL_TITLE"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>FEATURED_BOOKS.EXTERNAL_AUTHOR</code>.
     */
    val EXTERNAL_AUTHOR: TableField<FeaturedBooksRecord, String?> = createField(DSL.name("EXTERNAL_AUTHOR"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>FEATURED_BOOKS.RATING</code>.
     */
    val RATING: TableField<FeaturedBooksRecord, Float?> = createField(DSL.name("RATING"), SQLDataType.REAL.nullable(false), this, "")

    /**
     * The column <code>FEATURED_BOOKS.SOURCE_RANK</code>.
     */
    val SOURCE_RANK: TableField<FeaturedBooksRecord, Int?> = createField(DSL.name("SOURCE_RANK"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>FEATURED_BOOKS.FETCHED_AT</code>.
     */
    val FETCHED_AT: TableField<FeaturedBooksRecord, Instant?> = createField(DSL.name("FETCHED_AT"), SQLDataType.CLOB.nullable(false), this, "", KotlinInstantConverter())

    private constructor(alias: Name, aliased: Table<FeaturedBooksRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<FeaturedBooksRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<FeaturedBooksRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>FEATURED_BOOKS</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>FEATURED_BOOKS</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>FEATURED_BOOKS</code> table reference
     */
    constructor(): this(DSL.name("FEATURED_BOOKS"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, FeaturedBooksRecord>?, parentPath: InverseForeignKey<out Record, FeaturedBooksRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, FEATURED_BOOKS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class FeaturedBooksPath : FeaturedBooks, Path<FeaturedBooksRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, FeaturedBooksRecord>?, parentPath: InverseForeignKey<out Record, FeaturedBooksRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<FeaturedBooksRecord>): super(alias, aliased)
        override fun `as`(alias: String): FeaturedBooksPath = FeaturedBooksPath(DSL.name(alias), this)
        override fun `as`(alias: Name): FeaturedBooksPath = FeaturedBooksPath(alias, this)
        override fun `as`(alias: Table<*>): FeaturedBooksPath = FeaturedBooksPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_FEATURED_BOOKS_RATING, IDX_FEATURED_BOOKS_SOURCE_BOOK)
    override fun getIdentity(): Identity<FeaturedBooksRecord, Int?> = super.getIdentity() as Identity<FeaturedBooksRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<FeaturedBooksRecord> = FEATURED_BOOKS__PK_FEATURED_BOOKS
    override fun getReferences(): List<ForeignKey<FeaturedBooksRecord, *>> = listOf(FEATURED_BOOKS__FK_FEATURED_BOOKS_PK_BOOKS)

    /**
     * Get the implicit join path to the <code>BOOKS</code> table.
     */
    fun books(): BooksPath = books
    val books: BooksPath by lazy { BooksPath(this, FEATURED_BOOKS__FK_FEATURED_BOOKS_PK_BOOKS, null) }
    override fun `as`(alias: String): FeaturedBooks = FeaturedBooks(DSL.name(alias), this)
    override fun `as`(alias: Name): FeaturedBooks = FeaturedBooks(alias, this)
    override fun `as`(alias: Table<*>): FeaturedBooks = FeaturedBooks(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): FeaturedBooks = FeaturedBooks(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): FeaturedBooks = FeaturedBooks(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): FeaturedBooks = FeaturedBooks(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): FeaturedBooks = FeaturedBooks(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): FeaturedBooks = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): FeaturedBooks = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): FeaturedBooks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): FeaturedBooks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): FeaturedBooks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): FeaturedBooks = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): FeaturedBooks = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): FeaturedBooks = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): FeaturedBooks = where(DSL.notExists(select))
}
