/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.DefaultSchema
import io.heapy.kotbusta.jooq.indexes.IDX_GENRES_NAME
import io.heapy.kotbusta.jooq.keys.BOOK_GENRES__FK_BOOK_GENRES_PK_GENRES
import io.heapy.kotbusta.jooq.keys.GENRES__PK_GENRES
import io.heapy.kotbusta.jooq.keys.GENRES__UK_GENRES_1_99430152
import io.heapy.kotbusta.jooq.tables.BookGenres.BookGenresPath
import io.heapy.kotbusta.jooq.tables.Books.BooksPath
import io.heapy.kotbusta.jooq.tables.records.GenresRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Genres(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, GenresRecord>?,
    parentPath: InverseForeignKey<out Record, GenresRecord>?,
    aliased: Table<GenresRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<GenresRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>GENRES</code>
         */
        val GENRES: Genres = Genres()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<GenresRecord> = GenresRecord::class.java

    /**
     * The column <code>GENRES.ID</code>.
     */
    val ID: TableField<GenresRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.identity(true), this, "")

    /**
     * The column <code>GENRES.NAME</code>.
     */
    val NAME: TableField<GenresRecord, String?> = createField(DSL.name("NAME"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<GenresRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<GenresRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<GenresRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>GENRES</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>GENRES</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>GENRES</code> table reference
     */
    constructor(): this(DSL.name("GENRES"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GenresRecord>?, parentPath: InverseForeignKey<out Record, GenresRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, GENRES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class GenresPath : Genres, Path<GenresRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GenresRecord>?, parentPath: InverseForeignKey<out Record, GenresRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<GenresRecord>): super(alias, aliased)
        override fun `as`(alias: String): GenresPath = GenresPath(DSL.name(alias), this)
        override fun `as`(alias: Name): GenresPath = GenresPath(alias, this)
        override fun `as`(alias: Table<*>): GenresPath = GenresPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_GENRES_NAME)
    override fun getIdentity(): Identity<GenresRecord, Int?> = super.getIdentity() as Identity<GenresRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<GenresRecord> = GENRES__PK_GENRES
    override fun getUniqueKeys(): List<UniqueKey<GenresRecord>> = listOf(GENRES__UK_GENRES_1_99430152)

    private lateinit var _bookGenres: BookGenresPath

    /**
     * Get the implicit to-many join path to the <code>BOOK_GENRES</code> table
     */
    fun bookGenres(): BookGenresPath {
        if (!this::_bookGenres.isInitialized)
            _bookGenres = BookGenresPath(this, null, BOOK_GENRES__FK_BOOK_GENRES_PK_GENRES.inverseKey)

        return _bookGenres;
    }

    val bookGenres: BookGenresPath
        get(): BookGenresPath = bookGenres()

    /**
     * Get the implicit many-to-many join path to the <code>BOOKS</code> table
     */
    val books: BooksPath
        get(): BooksPath = bookGenres().books()
    override fun `as`(alias: String): Genres = Genres(DSL.name(alias), this)
    override fun `as`(alias: Name): Genres = Genres(alias, this)
    override fun `as`(alias: Table<*>): Genres = Genres(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Genres = Genres(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Genres = Genres(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Genres = Genres(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Genres = Genres(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Genres = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Genres = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Genres = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Genres = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Genres = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Genres = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Genres = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Genres = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Genres = where(DSL.notExists(select))
}
