/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.DefaultSchema
import io.heapy.kotbusta.jooq.indexes.IDX_IMPORT_JOBS_STARTED
import io.heapy.kotbusta.jooq.indexes.IDX_IMPORT_JOBS_STATUS
import io.heapy.kotbusta.jooq.indexes.IDX_IMPORT_JOBS_TYPE
import io.heapy.kotbusta.jooq.keys.IMPORT_JOBS__PK_IMPORT_JOBS
import io.heapy.kotbusta.jooq.tables.records.ImportJobsRecord

import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ImportJobs(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ImportJobsRecord>?,
    parentPath: InverseForeignKey<out Record, ImportJobsRecord>?,
    aliased: Table<ImportJobsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ImportJobsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>IMPORT_JOBS</code>
         */
        val IMPORT_JOBS: ImportJobs = ImportJobs()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ImportJobsRecord> = ImportJobsRecord::class.java

    /**
     * The column <code>IMPORT_JOBS.ID</code>.
     */
    val ID: TableField<ImportJobsRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.identity(true), this, "")

    /**
     * The column <code>IMPORT_JOBS.JOB_TYPE</code>.
     */
    val JOB_TYPE: TableField<ImportJobsRecord, String?> = createField(DSL.name("JOB_TYPE"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>IMPORT_JOBS.STATUS</code>.
     */
    val STATUS: TableField<ImportJobsRecord, String?> = createField(DSL.name("STATUS"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>IMPORT_JOBS.PROGRESS</code>.
     */
    val PROGRESS: TableField<ImportJobsRecord, String?> = createField(DSL.name("PROGRESS"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>IMPORT_JOBS.INP_FILES_PROCESSED</code>.
     */
    val INP_FILES_PROCESSED: TableField<ImportJobsRecord, Int?> = createField(DSL.name("INP_FILES_PROCESSED"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>IMPORT_JOBS.BOOKS_ADDED</code>.
     */
    val BOOKS_ADDED: TableField<ImportJobsRecord, Int?> = createField(DSL.name("BOOKS_ADDED"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>IMPORT_JOBS.BOOKS_UPDATED</code>.
     */
    val BOOKS_UPDATED: TableField<ImportJobsRecord, Int?> = createField(DSL.name("BOOKS_UPDATED"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>IMPORT_JOBS.BOOKS_DELETED</code>.
     */
    val BOOKS_DELETED: TableField<ImportJobsRecord, Int?> = createField(DSL.name("BOOKS_DELETED"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>IMPORT_JOBS.COVERS_ADDED</code>.
     */
    val COVERS_ADDED: TableField<ImportJobsRecord, Int?> = createField(DSL.name("COVERS_ADDED"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>IMPORT_JOBS.BOOK_ERRORS</code>.
     */
    val BOOK_ERRORS: TableField<ImportJobsRecord, Int?> = createField(DSL.name("BOOK_ERRORS"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>IMPORT_JOBS.COVER_ERRORS</code>.
     */
    val COVER_ERRORS: TableField<ImportJobsRecord, Int?> = createField(DSL.name("COVER_ERRORS"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>IMPORT_JOBS.ERROR_MESSAGE</code>.
     */
    val ERROR_MESSAGE: TableField<ImportJobsRecord, String?> = createField(DSL.name("ERROR_MESSAGE"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>IMPORT_JOBS.STARTED_AT</code>.
     */
    val STARTED_AT: TableField<ImportJobsRecord, Instant?> = createField(DSL.name("STARTED_AT"), SQLDataType.INSTANT.nullable(false), this, "")

    /**
     * The column <code>IMPORT_JOBS.COMPLETED_AT</code>.
     */
    val COMPLETED_AT: TableField<ImportJobsRecord, Instant?> = createField(DSL.name("COMPLETED_AT"), SQLDataType.INSTANT, this, "")

    /**
     * The column <code>IMPORT_JOBS.CREATED_AT</code>.
     */
    val CREATED_AT: TableField<ImportJobsRecord, Instant?> = createField(DSL.name("CREATED_AT"), SQLDataType.INSTANT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ImportJobsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ImportJobsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ImportJobsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>IMPORT_JOBS</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>IMPORT_JOBS</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>IMPORT_JOBS</code> table reference
     */
    constructor(): this(DSL.name("IMPORT_JOBS"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_IMPORT_JOBS_STARTED, IDX_IMPORT_JOBS_STATUS, IDX_IMPORT_JOBS_TYPE)
    override fun getIdentity(): Identity<ImportJobsRecord, Int?> = super.getIdentity() as Identity<ImportJobsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<ImportJobsRecord> = IMPORT_JOBS__PK_IMPORT_JOBS
    override fun getChecks(): List<Check<ImportJobsRecord>> = listOf(
        Internal.createCheck(this, DSL.name(""), "STATUS in ('RUNNING', 'COMPLETED', 'FAILED')", true)
    )
    override fun `as`(alias: String): ImportJobs = ImportJobs(DSL.name(alias), this)
    override fun `as`(alias: Name): ImportJobs = ImportJobs(alias, this)
    override fun `as`(alias: Table<*>): ImportJobs = ImportJobs(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ImportJobs = ImportJobs(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ImportJobs = ImportJobs(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ImportJobs = ImportJobs(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ImportJobs = ImportJobs(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ImportJobs = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ImportJobs = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ImportJobs = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ImportJobs = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ImportJobs = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ImportJobs = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ImportJobs = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ImportJobs = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ImportJobs = where(DSL.notExists(select))
}
