/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.DefaultSchema
import io.heapy.kotbusta.jooq.KotlinInstantConverter
import io.heapy.kotbusta.jooq.indexes.IDX_KINDLE_UPLOAD_QUEUE_DEVICE
import io.heapy.kotbusta.jooq.indexes.IDX_KINDLE_UPLOAD_QUEUE_NEXT_RUN
import io.heapy.kotbusta.jooq.indexes.IDX_KINDLE_UPLOAD_QUEUE_STATUS
import io.heapy.kotbusta.jooq.indexes.IDX_KINDLE_UPLOAD_QUEUE_USER
import io.heapy.kotbusta.jooq.keys.KINDLE_UPLOAD_QUEUE__FK_KINDLE_UPLOAD_QUEUE_PK_KINDLE_DEVICES
import io.heapy.kotbusta.jooq.keys.KINDLE_UPLOAD_QUEUE__FK_KINDLE_UPLOAD_QUEUE_PK_USERS
import io.heapy.kotbusta.jooq.keys.KINDLE_UPLOAD_QUEUE__PK_KINDLE_UPLOAD_QUEUE
import io.heapy.kotbusta.jooq.tables.KindleDevices.KindleDevicesPath
import io.heapy.kotbusta.jooq.tables.Users.UsersPath
import io.heapy.kotbusta.jooq.tables.records.KindleUploadQueueRecord

import kotlin.collections.Collection
import kotlin.collections.List
import kotlin.time.Instant

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class KindleUploadQueue(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, KindleUploadQueueRecord>?,
    parentPath: InverseForeignKey<out Record, KindleUploadQueueRecord>?,
    aliased: Table<KindleUploadQueueRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<KindleUploadQueueRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>KINDLE_UPLOAD_QUEUE</code>
         */
        val KINDLE_UPLOAD_QUEUE: KindleUploadQueue = KindleUploadQueue()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<KindleUploadQueueRecord> = KindleUploadQueueRecord::class.java

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.ID</code>.
     */
    val ID: TableField<KindleUploadQueueRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.generatedByDefaultAsIdentity(), this, "")

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.USER_ID</code>.
     */
    val USER_ID: TableField<KindleUploadQueueRecord, Int?> = createField(DSL.name("USER_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.DEVICE_ID</code>.
     */
    val DEVICE_ID: TableField<KindleUploadQueueRecord, Int?> = createField(DSL.name("DEVICE_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.FILE_NAME</code>.
     */
    val FILE_NAME: TableField<KindleUploadQueueRecord, String?> = createField(DSL.name("FILE_NAME"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.STORED_PATH</code>.
     */
    val STORED_PATH: TableField<KindleUploadQueueRecord, String?> = createField(DSL.name("STORED_PATH"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.SIZE_BYTES</code>.
     */
    val SIZE_BYTES: TableField<KindleUploadQueueRecord, Int?> = createField(DSL.name("SIZE_BYTES"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.SOURCE_FORMAT</code>.
     */
    val SOURCE_FORMAT: TableField<KindleUploadQueueRecord, String?> = createField(DSL.name("SOURCE_FORMAT"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.SEND_FORMAT</code>.
     */
    val SEND_FORMAT: TableField<KindleUploadQueueRecord, String?> = createField(DSL.name("SEND_FORMAT"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.STATUS</code>.
     */
    val STATUS: TableField<KindleUploadQueueRecord, String?> = createField(DSL.name("STATUS"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.ATTEMPTS</code>.
     */
    val ATTEMPTS: TableField<KindleUploadQueueRecord, Int?> = createField(DSL.name("ATTEMPTS"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.NEXT_RUN_AT</code>.
     */
    val NEXT_RUN_AT: TableField<KindleUploadQueueRecord, Instant?> = createField(DSL.name("NEXT_RUN_AT"), SQLDataType.CLOB.nullable(false), this, "", KotlinInstantConverter())

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.LAST_ERROR</code>.
     */
    val LAST_ERROR: TableField<KindleUploadQueueRecord, String?> = createField(DSL.name("LAST_ERROR"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.CREATED_AT</code>.
     */
    val CREATED_AT: TableField<KindleUploadQueueRecord, Instant?> = createField(DSL.name("CREATED_AT"), SQLDataType.CLOB.nullable(false), this, "", KotlinInstantConverter())

    /**
     * The column <code>KINDLE_UPLOAD_QUEUE.UPDATED_AT</code>.
     */
    val UPDATED_AT: TableField<KindleUploadQueueRecord, Instant?> = createField(DSL.name("UPDATED_AT"), SQLDataType.CLOB.nullable(false), this, "", KotlinInstantConverter())

    private constructor(alias: Name, aliased: Table<KindleUploadQueueRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<KindleUploadQueueRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<KindleUploadQueueRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>KINDLE_UPLOAD_QUEUE</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>KINDLE_UPLOAD_QUEUE</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>KINDLE_UPLOAD_QUEUE</code> table reference
     */
    constructor(): this(DSL.name("KINDLE_UPLOAD_QUEUE"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, KindleUploadQueueRecord>?, parentPath: InverseForeignKey<out Record, KindleUploadQueueRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, KINDLE_UPLOAD_QUEUE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class KindleUploadQueuePath : KindleUploadQueue, Path<KindleUploadQueueRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, KindleUploadQueueRecord>?, parentPath: InverseForeignKey<out Record, KindleUploadQueueRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<KindleUploadQueueRecord>): super(alias, aliased)
        override fun `as`(alias: String): KindleUploadQueuePath = KindleUploadQueuePath(DSL.name(alias), this)
        override fun `as`(alias: Name): KindleUploadQueuePath = KindleUploadQueuePath(alias, this)
        override fun `as`(alias: Table<*>): KindleUploadQueuePath = KindleUploadQueuePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_KINDLE_UPLOAD_QUEUE_DEVICE, IDX_KINDLE_UPLOAD_QUEUE_NEXT_RUN, IDX_KINDLE_UPLOAD_QUEUE_STATUS, IDX_KINDLE_UPLOAD_QUEUE_USER)
    override fun getIdentity(): Identity<KindleUploadQueueRecord, Int?> = super.getIdentity() as Identity<KindleUploadQueueRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<KindleUploadQueueRecord> = KINDLE_UPLOAD_QUEUE__PK_KINDLE_UPLOAD_QUEUE
    override fun getReferences(): List<ForeignKey<KindleUploadQueueRecord, *>> = listOf(KINDLE_UPLOAD_QUEUE__FK_KINDLE_UPLOAD_QUEUE_PK_KINDLE_DEVICES, KINDLE_UPLOAD_QUEUE__FK_KINDLE_UPLOAD_QUEUE_PK_USERS)

    /**
     * Get the implicit join path to the <code>KINDLE_DEVICES</code> table.
     */
    fun kindleDevices(): KindleDevicesPath = kindleDevices
    val kindleDevices: KindleDevicesPath by lazy { KindleDevicesPath(this, KINDLE_UPLOAD_QUEUE__FK_KINDLE_UPLOAD_QUEUE_PK_KINDLE_DEVICES, null) }

    /**
     * Get the implicit join path to the <code>USERS</code> table.
     */
    fun users(): UsersPath = users
    val users: UsersPath by lazy { UsersPath(this, KINDLE_UPLOAD_QUEUE__FK_KINDLE_UPLOAD_QUEUE_PK_USERS, null) }
    override fun `as`(alias: String): KindleUploadQueue = KindleUploadQueue(DSL.name(alias), this)
    override fun `as`(alias: Name): KindleUploadQueue = KindleUploadQueue(alias, this)
    override fun `as`(alias: Table<*>): KindleUploadQueue = KindleUploadQueue(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): KindleUploadQueue = KindleUploadQueue(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): KindleUploadQueue = KindleUploadQueue(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): KindleUploadQueue = KindleUploadQueue(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): KindleUploadQueue = KindleUploadQueue(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): KindleUploadQueue = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): KindleUploadQueue = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): KindleUploadQueue = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): KindleUploadQueue = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): KindleUploadQueue = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): KindleUploadQueue = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): KindleUploadQueue = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): KindleUploadQueue = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): KindleUploadQueue = where(DSL.notExists(select))
}
