/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.DefaultSchema
import io.heapy.kotbusta.jooq.indexes.IDX_KINDLE_SEND_EVENTS_QUEUE
import io.heapy.kotbusta.jooq.indexes.IDX_KINDLE_SEND_EVENTS_TYPE
import io.heapy.kotbusta.jooq.keys.KINDLE_SEND_EVENTS__FK_KINDLE_SEND_EVENTS_PK_KINDLE_SEND_QUEUE
import io.heapy.kotbusta.jooq.keys.KINDLE_SEND_EVENTS__PK_KINDLE_SEND_EVENTS
import io.heapy.kotbusta.jooq.tables.KindleSendQueue.KindleSendQueuePath
import io.heapy.kotbusta.jooq.tables.records.KindleSendEventsRecord

import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class KindleSendEvents(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, KindleSendEventsRecord>?,
    parentPath: InverseForeignKey<out Record, KindleSendEventsRecord>?,
    aliased: Table<KindleSendEventsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<KindleSendEventsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>KINDLE_SEND_EVENTS</code>
         */
        val KINDLE_SEND_EVENTS: KindleSendEvents = KindleSendEvents()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<KindleSendEventsRecord> = KindleSendEventsRecord::class.java

    /**
     * The column <code>KINDLE_SEND_EVENTS.ID</code>.
     */
    val ID: TableField<KindleSendEventsRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.identity(true), this, "")

    /**
     * The column <code>KINDLE_SEND_EVENTS.QUEUE_ID</code>.
     */
    val QUEUE_ID: TableField<KindleSendEventsRecord, Int?> = createField(DSL.name("QUEUE_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KINDLE_SEND_EVENTS.EVENT_TYPE</code>.
     */
    val EVENT_TYPE: TableField<KindleSendEventsRecord, String?> = createField(DSL.name("EVENT_TYPE"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>KINDLE_SEND_EVENTS.DETAILS</code>.
     */
    val DETAILS: TableField<KindleSendEventsRecord, String?> = createField(DSL.name("DETAILS"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>KINDLE_SEND_EVENTS.CREATED_AT</code>.
     */
    val CREATED_AT: TableField<KindleSendEventsRecord, Instant?> = createField(DSL.name("CREATED_AT"), SQLDataType.INSTANT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<KindleSendEventsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<KindleSendEventsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<KindleSendEventsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>KINDLE_SEND_EVENTS</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>KINDLE_SEND_EVENTS</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>KINDLE_SEND_EVENTS</code> table reference
     */
    constructor(): this(DSL.name("KINDLE_SEND_EVENTS"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, KindleSendEventsRecord>?, parentPath: InverseForeignKey<out Record, KindleSendEventsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, KINDLE_SEND_EVENTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class KindleSendEventsPath : KindleSendEvents, Path<KindleSendEventsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, KindleSendEventsRecord>?, parentPath: InverseForeignKey<out Record, KindleSendEventsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<KindleSendEventsRecord>): super(alias, aliased)
        override fun `as`(alias: String): KindleSendEventsPath = KindleSendEventsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): KindleSendEventsPath = KindleSendEventsPath(alias, this)
        override fun `as`(alias: Table<*>): KindleSendEventsPath = KindleSendEventsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_KINDLE_SEND_EVENTS_QUEUE, IDX_KINDLE_SEND_EVENTS_TYPE)
    override fun getIdentity(): Identity<KindleSendEventsRecord, Int?> = super.getIdentity() as Identity<KindleSendEventsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<KindleSendEventsRecord> = KINDLE_SEND_EVENTS__PK_KINDLE_SEND_EVENTS
    override fun getReferences(): List<ForeignKey<KindleSendEventsRecord, *>> = listOf(KINDLE_SEND_EVENTS__FK_KINDLE_SEND_EVENTS_PK_KINDLE_SEND_QUEUE)

    /**
     * Get the implicit join path to the <code>KINDLE_SEND_QUEUE</code> table.
     */
    fun kindleSendQueue(): KindleSendQueuePath = kindleSendQueue
    val kindleSendQueue: KindleSendQueuePath by lazy { KindleSendQueuePath(this, KINDLE_SEND_EVENTS__FK_KINDLE_SEND_EVENTS_PK_KINDLE_SEND_QUEUE, null) }
    override fun `as`(alias: String): KindleSendEvents = KindleSendEvents(DSL.name(alias), this)
    override fun `as`(alias: Name): KindleSendEvents = KindleSendEvents(alias, this)
    override fun `as`(alias: Table<*>): KindleSendEvents = KindleSendEvents(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): KindleSendEvents = KindleSendEvents(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): KindleSendEvents = KindleSendEvents(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): KindleSendEvents = KindleSendEvents(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): KindleSendEvents = KindleSendEvents(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): KindleSendEvents = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): KindleSendEvents = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): KindleSendEvents = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): KindleSendEvents = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): KindleSendEvents = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): KindleSendEvents = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): KindleSendEvents = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): KindleSendEvents = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): KindleSendEvents = where(DSL.notExists(select))
}
