/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.DefaultSchema
import io.heapy.kotbusta.jooq.keys.BOOKS__FK_BOOKS_PK_SERIES
import io.heapy.kotbusta.jooq.keys.SERIES__PK_SERIES
import io.heapy.kotbusta.jooq.tables.Books.BooksPath
import io.heapy.kotbusta.jooq.tables.records.SeriesRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Series(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SeriesRecord>?,
    parentPath: InverseForeignKey<out Record, SeriesRecord>?,
    aliased: Table<SeriesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SeriesRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>SERIES</code>
         */
        val SERIES: Series = Series()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SeriesRecord> = SeriesRecord::class.java

    /**
     * The column <code>SERIES.ID</code>.
     */
    val ID: TableField<SeriesRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.identity(true), this, "")

    /**
     * The column <code>SERIES.NAME</code>.
     */
    val NAME: TableField<SeriesRecord, String?> = createField(DSL.name("NAME"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<SeriesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<SeriesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<SeriesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>SERIES</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>SERIES</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>SERIES</code> table reference
     */
    constructor(): this(DSL.name("SERIES"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, SeriesRecord>?, parentPath: InverseForeignKey<out Record, SeriesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, SERIES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class SeriesPath : Series, Path<SeriesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, SeriesRecord>?, parentPath: InverseForeignKey<out Record, SeriesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<SeriesRecord>): super(alias, aliased)
        override fun `as`(alias: String): SeriesPath = SeriesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): SeriesPath = SeriesPath(alias, this)
        override fun `as`(alias: Table<*>): SeriesPath = SeriesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<SeriesRecord, Int?> = super.getIdentity() as Identity<SeriesRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<SeriesRecord> = SERIES__PK_SERIES

    private lateinit var _books: BooksPath

    /**
     * Get the implicit to-many join path to the <code>BOOKS</code> table
     */
    fun books(): BooksPath {
        if (!this::_books.isInitialized)
            _books = BooksPath(this, null, BOOKS__FK_BOOKS_PK_SERIES.inverseKey)

        return _books;
    }

    val books: BooksPath
        get(): BooksPath = books()
    override fun `as`(alias: String): Series = Series(DSL.name(alias), this)
    override fun `as`(alias: Name): Series = Series(alias, this)
    override fun `as`(alias: Table<*>): Series = Series(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Series = Series(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Series = Series(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Series = Series(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Series = Series(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Series = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Series = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Series = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Series = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Series = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Series = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Series = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Series = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Series = where(DSL.notExists(select))
}
