/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.DefaultSchema
import io.heapy.kotbusta.jooq.KotlinInstantConverter
import io.heapy.kotbusta.jooq.indexes.IDX_USER_COMMENTS_BOOK
import io.heapy.kotbusta.jooq.indexes.IDX_USER_COMMENTS_USER
import io.heapy.kotbusta.jooq.keys.USER_COMMENTS__FK_USER_COMMENTS_PK_BOOKS
import io.heapy.kotbusta.jooq.keys.USER_COMMENTS__FK_USER_COMMENTS_PK_USERS
import io.heapy.kotbusta.jooq.keys.USER_COMMENTS__PK_USER_COMMENTS
import io.heapy.kotbusta.jooq.tables.Books.BooksPath
import io.heapy.kotbusta.jooq.tables.Users.UsersPath
import io.heapy.kotbusta.jooq.tables.records.UserCommentsRecord

import kotlin.collections.Collection
import kotlin.collections.List
import kotlin.time.Instant

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UserComments(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UserCommentsRecord>?,
    parentPath: InverseForeignKey<out Record, UserCommentsRecord>?,
    aliased: Table<UserCommentsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UserCommentsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>USER_COMMENTS</code>
         */
        val USER_COMMENTS: UserComments = UserComments()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserCommentsRecord> = UserCommentsRecord::class.java

    /**
     * The column <code>USER_COMMENTS.ID</code>.
     */
    val ID: TableField<UserCommentsRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.identity(true), this, "")

    /**
     * The column <code>USER_COMMENTS.USER_ID</code>.
     */
    val USER_ID: TableField<UserCommentsRecord, Int?> = createField(DSL.name("USER_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>USER_COMMENTS.BOOK_ID</code>.
     */
    val BOOK_ID: TableField<UserCommentsRecord, Int?> = createField(DSL.name("BOOK_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>USER_COMMENTS.COMMENT</code>.
     */
    val COMMENT: TableField<UserCommentsRecord, String?> = createField(DSL.name("COMMENT"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>USER_COMMENTS.CREATED_AT</code>.
     */
    val CREATED_AT: TableField<UserCommentsRecord, Instant?> = createField(DSL.name("CREATED_AT"), SQLDataType.CLOB.nullable(false), this, "", KotlinInstantConverter())

    /**
     * The column <code>USER_COMMENTS.UPDATED_AT</code>.
     */
    val UPDATED_AT: TableField<UserCommentsRecord, Instant?> = createField(DSL.name("UPDATED_AT"), SQLDataType.CLOB.nullable(false), this, "", KotlinInstantConverter())

    private constructor(alias: Name, aliased: Table<UserCommentsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UserCommentsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UserCommentsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>USER_COMMENTS</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>USER_COMMENTS</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>USER_COMMENTS</code> table reference
     */
    constructor(): this(DSL.name("USER_COMMENTS"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserCommentsRecord>?, parentPath: InverseForeignKey<out Record, UserCommentsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, USER_COMMENTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class UserCommentsPath : UserComments, Path<UserCommentsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserCommentsRecord>?, parentPath: InverseForeignKey<out Record, UserCommentsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UserCommentsRecord>): super(alias, aliased)
        override fun `as`(alias: String): UserCommentsPath = UserCommentsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): UserCommentsPath = UserCommentsPath(alias, this)
        override fun `as`(alias: Table<*>): UserCommentsPath = UserCommentsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_USER_COMMENTS_BOOK, IDX_USER_COMMENTS_USER)
    override fun getIdentity(): Identity<UserCommentsRecord, Int?> = super.getIdentity() as Identity<UserCommentsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<UserCommentsRecord> = USER_COMMENTS__PK_USER_COMMENTS
    override fun getReferences(): List<ForeignKey<UserCommentsRecord, *>> = listOf(USER_COMMENTS__FK_USER_COMMENTS_PK_BOOKS, USER_COMMENTS__FK_USER_COMMENTS_PK_USERS)

    /**
     * Get the implicit join path to the <code>BOOKS</code> table.
     */
    fun books(): BooksPath = books
    val books: BooksPath by lazy { BooksPath(this, USER_COMMENTS__FK_USER_COMMENTS_PK_BOOKS, null) }

    /**
     * Get the implicit join path to the <code>USERS</code> table.
     */
    fun users(): UsersPath = users
    val users: UsersPath by lazy { UsersPath(this, USER_COMMENTS__FK_USER_COMMENTS_PK_USERS, null) }
    override fun `as`(alias: String): UserComments = UserComments(DSL.name(alias), this)
    override fun `as`(alias: Name): UserComments = UserComments(alias, this)
    override fun `as`(alias: Table<*>): UserComments = UserComments(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserComments = UserComments(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserComments = UserComments(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserComments = UserComments(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): UserComments = UserComments(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): UserComments = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): UserComments = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): UserComments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): UserComments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): UserComments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): UserComments = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): UserComments = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): UserComments = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): UserComments = where(DSL.notExists(select))
}
