/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.DefaultSchema
import io.heapy.kotbusta.jooq.keys.USER_NOTES__FK_USER_NOTES_PK_BOOKS
import io.heapy.kotbusta.jooq.keys.USER_NOTES__FK_USER_NOTES_PK_USERS
import io.heapy.kotbusta.jooq.keys.USER_NOTES__PK_USER_NOTES
import io.heapy.kotbusta.jooq.tables.Books.BooksPath
import io.heapy.kotbusta.jooq.tables.Users.UsersPath
import io.heapy.kotbusta.jooq.tables.records.UserNotesRecord

import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UserNotes(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UserNotesRecord>?,
    parentPath: InverseForeignKey<out Record, UserNotesRecord>?,
    aliased: Table<UserNotesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UserNotesRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>USER_NOTES</code>
         */
        val USER_NOTES: UserNotes = UserNotes()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserNotesRecord> = UserNotesRecord::class.java

    /**
     * The column <code>USER_NOTES.ID</code>.
     */
    val ID: TableField<UserNotesRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.identity(true), this, "")

    /**
     * The column <code>USER_NOTES.USER_ID</code>.
     */
    val USER_ID: TableField<UserNotesRecord, Int?> = createField(DSL.name("USER_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>USER_NOTES.BOOK_ID</code>.
     */
    val BOOK_ID: TableField<UserNotesRecord, Int?> = createField(DSL.name("BOOK_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>USER_NOTES.NOTE</code>.
     */
    val NOTE: TableField<UserNotesRecord, String?> = createField(DSL.name("NOTE"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>USER_NOTES.IS_PRIVATE</code>.
     */
    val IS_PRIVATE: TableField<UserNotesRecord, Int?> = createField(DSL.name("IS_PRIVATE"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>USER_NOTES.CREATED_AT</code>.
     */
    val CREATED_AT: TableField<UserNotesRecord, Instant?> = createField(DSL.name("CREATED_AT"), SQLDataType.INSTANT.nullable(false), this, "")

    /**
     * The column <code>USER_NOTES.UPDATED_AT</code>.
     */
    val UPDATED_AT: TableField<UserNotesRecord, Instant?> = createField(DSL.name("UPDATED_AT"), SQLDataType.INSTANT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UserNotesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UserNotesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UserNotesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>USER_NOTES</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>USER_NOTES</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>USER_NOTES</code> table reference
     */
    constructor(): this(DSL.name("USER_NOTES"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserNotesRecord>?, parentPath: InverseForeignKey<out Record, UserNotesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, USER_NOTES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class UserNotesPath : UserNotes, Path<UserNotesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserNotesRecord>?, parentPath: InverseForeignKey<out Record, UserNotesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UserNotesRecord>): super(alias, aliased)
        override fun `as`(alias: String): UserNotesPath = UserNotesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): UserNotesPath = UserNotesPath(alias, this)
        override fun `as`(alias: Table<*>): UserNotesPath = UserNotesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<UserNotesRecord, Int?> = super.getIdentity() as Identity<UserNotesRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<UserNotesRecord> = USER_NOTES__PK_USER_NOTES
    override fun getReferences(): List<ForeignKey<UserNotesRecord, *>> = listOf(USER_NOTES__FK_USER_NOTES_PK_BOOKS, USER_NOTES__FK_USER_NOTES_PK_USERS)

    /**
     * Get the implicit join path to the <code>BOOKS</code> table.
     */
    fun books(): BooksPath = books
    val books: BooksPath by lazy { BooksPath(this, USER_NOTES__FK_USER_NOTES_PK_BOOKS, null) }

    /**
     * Get the implicit join path to the <code>USERS</code> table.
     */
    fun users(): UsersPath = users
    val users: UsersPath by lazy { UsersPath(this, USER_NOTES__FK_USER_NOTES_PK_USERS, null) }
    override fun `as`(alias: String): UserNotes = UserNotes(DSL.name(alias), this)
    override fun `as`(alias: Name): UserNotes = UserNotes(alias, this)
    override fun `as`(alias: Table<*>): UserNotes = UserNotes(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserNotes = UserNotes(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserNotes = UserNotes(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserNotes = UserNotes(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): UserNotes = UserNotes(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): UserNotes = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): UserNotes = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): UserNotes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): UserNotes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): UserNotes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): UserNotes = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): UserNotes = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): UserNotes = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): UserNotes = where(DSL.notExists(select))
}
