/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables


import io.heapy.kotbusta.jooq.DefaultSchema
import io.heapy.kotbusta.jooq.KotlinInstantConverter
import io.heapy.kotbusta.jooq.keys.KINDLE_DEVICES__FK_KINDLE_DEVICES_PK_USERS
import io.heapy.kotbusta.jooq.keys.KINDLE_SEND_QUEUE__FK_KINDLE_SEND_QUEUE_PK_USERS
import io.heapy.kotbusta.jooq.keys.USERS__PK_USERS
import io.heapy.kotbusta.jooq.keys.USERS__UK_USERS_1_34197334
import io.heapy.kotbusta.jooq.tables.KindleDevices.KindleDevicesPath
import io.heapy.kotbusta.jooq.tables.KindleSendQueue.KindleSendQueuePath
import io.heapy.kotbusta.jooq.tables.records.UsersRecord

import kotlin.collections.Collection
import kotlin.collections.List
import kotlin.time.Instant

import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Users(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UsersRecord>?,
    parentPath: InverseForeignKey<out Record, UsersRecord>?,
    aliased: Table<UsersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UsersRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>USERS</code>
         */
        val USERS: Users = Users()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UsersRecord> = UsersRecord::class.java

    /**
     * The column <code>USERS.ID</code>.
     */
    val ID: TableField<UsersRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.generatedByDefaultAsIdentity(), this, "")

    /**
     * The column <code>USERS.GOOGLE_ID</code>.
     */
    val GOOGLE_ID: TableField<UsersRecord, String?> = createField(DSL.name("GOOGLE_ID"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>USERS.EMAIL</code>.
     */
    val EMAIL: TableField<UsersRecord, String?> = createField(DSL.name("EMAIL"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>USERS.NAME</code>.
     */
    val NAME: TableField<UsersRecord, String?> = createField(DSL.name("NAME"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>USERS.AVATAR_URL</code>.
     */
    val AVATAR_URL: TableField<UsersRecord, String?> = createField(DSL.name("AVATAR_URL"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>USERS.STATUS</code>.
     */
    val STATUS: TableField<UsersRecord, String?> = createField(DSL.name("STATUS"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>USERS.CREATED_AT</code>.
     */
    val CREATED_AT: TableField<UsersRecord, Instant?> = createField(DSL.name("CREATED_AT"), SQLDataType.CLOB.nullable(false), this, "", KotlinInstantConverter())

    /**
     * The column <code>USERS.UPDATED_AT</code>.
     */
    val UPDATED_AT: TableField<UsersRecord, Instant?> = createField(DSL.name("UPDATED_AT"), SQLDataType.CLOB.nullable(false), this, "", KotlinInstantConverter())

    private constructor(alias: Name, aliased: Table<UsersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UsersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UsersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>USERS</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>USERS</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>USERS</code> table reference
     */
    constructor(): this(DSL.name("USERS"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UsersRecord>?, parentPath: InverseForeignKey<out Record, UsersRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, USERS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class UsersPath : Users, Path<UsersRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UsersRecord>?, parentPath: InverseForeignKey<out Record, UsersRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UsersRecord>): super(alias, aliased)
        override fun `as`(alias: String): UsersPath = UsersPath(DSL.name(alias), this)
        override fun `as`(alias: Name): UsersPath = UsersPath(alias, this)
        override fun `as`(alias: Table<*>): UsersPath = UsersPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<UsersRecord, Int?> = super.getIdentity() as Identity<UsersRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<UsersRecord> = USERS__PK_USERS
    override fun getUniqueKeys(): List<UniqueKey<UsersRecord>> = listOf(USERS__UK_USERS_1_34197334)

    private lateinit var _kindleDevices: KindleDevicesPath

    /**
     * Get the implicit to-many join path to the <code>KINDLE_DEVICES</code>
     * table
     */
    fun kindleDevices(): KindleDevicesPath {
        if (!this::_kindleDevices.isInitialized)
            _kindleDevices = KindleDevicesPath(this, null, KINDLE_DEVICES__FK_KINDLE_DEVICES_PK_USERS.inverseKey)

        return _kindleDevices;
    }

    val kindleDevices: KindleDevicesPath
        get(): KindleDevicesPath = kindleDevices()

    private lateinit var _kindleSendQueue: KindleSendQueuePath

    /**
     * Get the implicit to-many join path to the <code>KINDLE_SEND_QUEUE</code>
     * table
     */
    fun kindleSendQueue(): KindleSendQueuePath {
        if (!this::_kindleSendQueue.isInitialized)
            _kindleSendQueue = KindleSendQueuePath(this, null, KINDLE_SEND_QUEUE__FK_KINDLE_SEND_QUEUE_PK_USERS.inverseKey)

        return _kindleSendQueue;
    }

    val kindleSendQueue: KindleSendQueuePath
        get(): KindleSendQueuePath = kindleSendQueue()
    override fun getChecks(): List<Check<UsersRecord>> = listOf(
        Internal.createCheck(this, DSL.name(""), "STATUS in ('PENDING', 'APPROVED', 'REJECTED', 'DEACTIVATED')", true)
    )
    override fun `as`(alias: String): Users = Users(DSL.name(alias), this)
    override fun `as`(alias: Name): Users = Users(alias, this)
    override fun `as`(alias: Table<*>): Users = Users(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Users = Users(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Users = Users(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Users = Users(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Users = Users(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Users = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Users = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Users = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Users = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): Users = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): Users = where(DSL.notExists(select))
}
