# docker compose up -d
name: "kotbusta-prod"

services:
  service:
    image: "ghcr.io/heapy/kotbusta:main"
    restart: "always"
    mem_limit: "256m"
    memswap_limit: "0m"
    environment:
      KOTBUSTA_OPTS: "-Xmx200m"
      KOTBUSTA_GOOGLE_CLIENT_ID: "${KOTBUSTA_GOOGLE_CLIENT_ID}"
      KOTBUSTA_GOOGLE_CLIENT_SECRET: "${KOTBUSTA_GOOGLE_CLIENT_SECRET}"
      KOTBUSTA_GOOGLE_REDIRECT_URI: "${KOTBUSTA_GOOGLE_REDIRECT_URI}"
      KOTBUSTA_SESSION_SIGN_KEY: "${KOTBUSTA_SESSION_SIGN_KEY}"
      KOTBUSTA_SESSION_ENCRYPT_KEY: "${KOTBUSTA_SESSION_ENCRYPT_KEY}"
      KOTBUSTA_DB_PATH: "${KOTBUSTA_DB_PATH}"
      KOTBUSTA_ADMIN_EMAIL: "${KOTBUSTA_ADMIN_EMAIL}"
      KOTBUSTA_BOOKS_DATA_PATH: "/data/books"
    volumes:
      - "dbdata:/data/db"
      - "books:/data/books"
    ports:
      - "8080:8080"
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      device: "${KOTBUSTA_DB_DATA_PATH_LOCAL}"
      o: bind
  books:
    driver: local
    driver_opts:
      type: none
      device: "${KOTBUSTA_BOOKS_DATA_PATH_LOCAL}"
      o: bind,ro
