@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.references


import io.heapy.kotbusta.jooq.tables.Authors
import io.heapy.kotbusta.jooq.tables.BookAuthors
import io.heapy.kotbusta.jooq.tables.Books
import io.heapy.kotbusta.jooq.tables.Downloads
import io.heapy.kotbusta.jooq.tables.ImportJobs
import io.heapy.kotbusta.jooq.tables.Series
import io.heapy.kotbusta.jooq.tables.UserComments
import io.heapy.kotbusta.jooq.tables.UserNotes
import io.heapy.kotbusta.jooq.tables.UserStars
import io.heapy.kotbusta.jooq.tables.Users



/**
 * The table <code>public.authors</code>.
 */
val AUTHORS: Authors = Authors.AUTHORS

/**
 * The table <code>public.book_authors</code>.
 */
val BOOK_AUTHORS: BookAuthors = BookAuthors.BOOK_AUTHORS

/**
 * The table <code>public.books</code>.
 */
val BOOKS: Books = Books.BOOKS

/**
 * The table <code>public.downloads</code>.
 */
val DOWNLOADS: Downloads = Downloads.DOWNLOADS

/**
 * The table <code>public.import_jobs</code>.
 */
val IMPORT_JOBS: ImportJobs = ImportJobs.IMPORT_JOBS

/**
 * The table <code>public.series</code>.
 */
val SERIES: Series = Series.SERIES

/**
 * The table <code>public.user_comments</code>.
 */
val USER_COMMENTS: UserComments = UserComments.USER_COMMENTS

/**
 * The table <code>public.user_notes</code>.
 */
val USER_NOTES: UserNotes = UserNotes.USER_NOTES

/**
 * The table <code>public.user_stars</code>.
 */
val USER_STARS: UserStars = UserStars.USER_STARS

/**
 * The table <code>public.users</code>.
 */
val USERS: Users = Users.USERS
