/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.daos


import io.heapy.kotbusta.jooq.tables.Downloads
import io.heapy.kotbusta.jooq.tables.records.DownloadsRecord

import java.time.OffsetDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DownloadsDao(configuration: Configuration?) : DAOImpl<DownloadsRecord, io.heapy.kotbusta.jooq.tables.pojos.Downloads, Long>(Downloads.DOWNLOADS, io.heapy.kotbusta.jooq.tables.pojos.Downloads::class.java, configuration) {

    /**
     * Create a new DownloadsDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.kotbusta.jooq.tables.pojos.Downloads): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.kotbusta.jooq.tables.pojos.Downloads> = fetchRange(Downloads.DOWNLOADS.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.kotbusta.jooq.tables.pojos.Downloads> = fetch(Downloads.DOWNLOADS.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.kotbusta.jooq.tables.pojos.Downloads? = fetchOne(Downloads.DOWNLOADS.ID, value)

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUserId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbusta.jooq.tables.pojos.Downloads> = fetchRange(Downloads.DOWNLOADS.USER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    fun fetchByUserId(vararg values: Long): List<io.heapy.kotbusta.jooq.tables.pojos.Downloads> = fetch(Downloads.DOWNLOADS.USER_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>book_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfBookId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbusta.jooq.tables.pojos.Downloads> = fetchRange(Downloads.DOWNLOADS.BOOK_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>book_id IN (values)</code>
     */
    fun fetchByBookId(vararg values: Long): List<io.heapy.kotbusta.jooq.tables.pojos.Downloads> = fetch(Downloads.DOWNLOADS.BOOK_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>format BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfFormat(lowerInclusive: String, upperInclusive: String): List<io.heapy.kotbusta.jooq.tables.pojos.Downloads> = fetchRange(Downloads.DOWNLOADS.FORMAT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>format IN (values)</code>
     */
    fun fetchByFormat(vararg values: String): List<io.heapy.kotbusta.jooq.tables.pojos.Downloads> = fetch(Downloads.DOWNLOADS.FORMAT, *values)

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreatedAt(lowerInclusive: OffsetDateTime?, upperInclusive: OffsetDateTime?): List<io.heapy.kotbusta.jooq.tables.pojos.Downloads> = fetchRange(Downloads.DOWNLOADS.CREATED_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    fun fetchByCreatedAt(vararg values: OffsetDateTime): List<io.heapy.kotbusta.jooq.tables.pojos.Downloads> = fetch(Downloads.DOWNLOADS.CREATED_AT, *values)
}
