@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.indexes


import io.heapy.kotbusta.jooq.tables.Authors
import io.heapy.kotbusta.jooq.tables.BookAuthors
import io.heapy.kotbusta.jooq.tables.BookEnrichment
import io.heapy.kotbusta.jooq.tables.BookGenres
import io.heapy.kotbusta.jooq.tables.Books
import io.heapy.kotbusta.jooq.tables.FeaturedBooks
import io.heapy.kotbusta.jooq.tables.Genres
import io.heapy.kotbusta.jooq.tables.KindleDevices
import io.heapy.kotbusta.jooq.tables.KindleSendEvents
import io.heapy.kotbusta.jooq.tables.KindleSendQueue

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_AUTHORS_NAME: Index = Internal.createIndex(DSL.name("IDX_AUTHORS_NAME"), Authors.AUTHORS, arrayOf(Authors.AUTHORS.FULL_NAME), false)
val IDX_BOOK_AUTHORS_AUTHOR: Index = Internal.createIndex(DSL.name("IDX_BOOK_AUTHORS_AUTHOR"), BookAuthors.BOOK_AUTHORS, arrayOf(BookAuthors.BOOK_AUTHORS.AUTHOR_ID), false)
val IDX_BOOK_AUTHORS_BOOK: Index = Internal.createIndex(DSL.name("IDX_BOOK_AUTHORS_BOOK"), BookAuthors.BOOK_AUTHORS, arrayOf(BookAuthors.BOOK_AUTHORS.BOOK_ID), false)
val IDX_BOOK_ENRICHMENT_STATUS: Index = Internal.createIndex(DSL.name("IDX_BOOK_ENRICHMENT_STATUS"), BookEnrichment.BOOK_ENRICHMENT, arrayOf(BookEnrichment.BOOK_ENRICHMENT.STATUS), false)
val IDX_BOOK_GENRES_BOOK: Index = Internal.createIndex(DSL.name("IDX_BOOK_GENRES_BOOK"), BookGenres.BOOK_GENRES, arrayOf(BookGenres.BOOK_GENRES.BOOK_ID), false)
val IDX_BOOK_GENRES_GENRE: Index = Internal.createIndex(DSL.name("IDX_BOOK_GENRES_GENRE"), BookGenres.BOOK_GENRES, arrayOf(BookGenres.BOOK_GENRES.GENRE_ID), false)
val IDX_BOOKS_LANGUAGE: Index = Internal.createIndex(DSL.name("IDX_BOOKS_LANGUAGE"), Books.BOOKS, arrayOf(Books.BOOKS.LANGUAGE), false)
val IDX_BOOKS_SERIES: Index = Internal.createIndex(DSL.name("IDX_BOOKS_SERIES"), Books.BOOKS, arrayOf(Books.BOOKS.SERIES_ID), false)
val IDX_BOOKS_TITLE: Index = Internal.createIndex(DSL.name("IDX_BOOKS_TITLE"), Books.BOOKS, arrayOf(Books.BOOKS.TITLE), false)
val IDX_FEATURED_BOOKS_RATING: Index = Internal.createIndex(DSL.name("IDX_FEATURED_BOOKS_RATING"), FeaturedBooks.FEATURED_BOOKS, arrayOf(FeaturedBooks.FEATURED_BOOKS.SOURCE, FeaturedBooks.FEATURED_BOOKS.RATING), false)
val IDX_FEATURED_BOOKS_SOURCE_BOOK: Index = Internal.createIndex(DSL.name("IDX_FEATURED_BOOKS_SOURCE_BOOK"), FeaturedBooks.FEATURED_BOOKS, arrayOf(FeaturedBooks.FEATURED_BOOKS.SOURCE, FeaturedBooks.FEATURED_BOOKS.BOOK_ID), true)
val IDX_GENRES_NAME: Index = Internal.createIndex(DSL.name("IDX_GENRES_NAME"), Genres.GENRES, arrayOf(Genres.GENRES.NAME), false)
val IDX_KINDLE_DEVICES_EMAIL: Index = Internal.createIndex(DSL.name("IDX_KINDLE_DEVICES_EMAIL"), KindleDevices.KINDLE_DEVICES, arrayOf(KindleDevices.KINDLE_DEVICES.EMAIL), false)
val IDX_KINDLE_DEVICES_USER: Index = Internal.createIndex(DSL.name("IDX_KINDLE_DEVICES_USER"), KindleDevices.KINDLE_DEVICES, arrayOf(KindleDevices.KINDLE_DEVICES.USER_ID), false)
val IDX_KINDLE_SEND_EVENTS_QUEUE: Index = Internal.createIndex(DSL.name("IDX_KINDLE_SEND_EVENTS_QUEUE"), KindleSendEvents.KINDLE_SEND_EVENTS, arrayOf(KindleSendEvents.KINDLE_SEND_EVENTS.QUEUE_ID), false)
val IDX_KINDLE_SEND_EVENTS_TYPE: Index = Internal.createIndex(DSL.name("IDX_KINDLE_SEND_EVENTS_TYPE"), KindleSendEvents.KINDLE_SEND_EVENTS, arrayOf(KindleSendEvents.KINDLE_SEND_EVENTS.EVENT_TYPE), false)
val IDX_KINDLE_SEND_QUEUE_BOOK: Index = Internal.createIndex(DSL.name("IDX_KINDLE_SEND_QUEUE_BOOK"), KindleSendQueue.KINDLE_SEND_QUEUE, arrayOf(KindleSendQueue.KINDLE_SEND_QUEUE.BOOK_ID), false)
val IDX_KINDLE_SEND_QUEUE_DEVICE: Index = Internal.createIndex(DSL.name("IDX_KINDLE_SEND_QUEUE_DEVICE"), KindleSendQueue.KINDLE_SEND_QUEUE, arrayOf(KindleSendQueue.KINDLE_SEND_QUEUE.DEVICE_ID), false)
val IDX_KINDLE_SEND_QUEUE_NEXT_RUN: Index = Internal.createIndex(DSL.name("IDX_KINDLE_SEND_QUEUE_NEXT_RUN"), KindleSendQueue.KINDLE_SEND_QUEUE, arrayOf(KindleSendQueue.KINDLE_SEND_QUEUE.NEXT_RUN_AT), false)
val IDX_KINDLE_SEND_QUEUE_STATUS: Index = Internal.createIndex(DSL.name("IDX_KINDLE_SEND_QUEUE_STATUS"), KindleSendQueue.KINDLE_SEND_QUEUE, arrayOf(KindleSendQueue.KINDLE_SEND_QUEUE.STATUS), false)
val IDX_KINDLE_SEND_QUEUE_USER: Index = Internal.createIndex(DSL.name("IDX_KINDLE_SEND_QUEUE_USER"), KindleSendQueue.KINDLE_SEND_QUEUE, arrayOf(KindleSendQueue.KINDLE_SEND_QUEUE.USER_ID), false)
