@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.indexes


import io.heapy.kotbusta.jooq.tables.Authors
import io.heapy.kotbusta.jooq.tables.Books
import io.heapy.kotbusta.jooq.tables.Downloads
import io.heapy.kotbusta.jooq.tables.ImportJobs
import io.heapy.kotbusta.jooq.tables.UserComments

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_AUTHORS_NAME: Index = Internal.createIndex(DSL.name("idx_authors_name"), Authors.AUTHORS, arrayOf(Authors.AUTHORS.LAST_NAME, Authors.AUTHORS.FIRST_NAME), false)
val IDX_BOOKS_GENRE: Index = Internal.createIndex(DSL.name("idx_books_genre"), Books.BOOKS, arrayOf(Books.BOOKS.GENRE), false)
val IDX_BOOKS_LANGUAGE: Index = Internal.createIndex(DSL.name("idx_books_language"), Books.BOOKS, arrayOf(Books.BOOKS.LANGUAGE), false)
val IDX_BOOKS_SERIES: Index = Internal.createIndex(DSL.name("idx_books_series"), Books.BOOKS, arrayOf(Books.BOOKS.SERIES_ID), false)
val IDX_BOOKS_TITLE: Index = Internal.createIndex(DSL.name("idx_books_title"), Books.BOOKS, arrayOf(Books.BOOKS.TITLE), false)
val IDX_DOWNLOADS_RECENT: Index = Internal.createIndex(DSL.name("idx_downloads_recent"), Downloads.DOWNLOADS, arrayOf(Downloads.DOWNLOADS.CREATED_AT.desc()), false)
val IDX_IMPORT_JOBS_STARTED: Index = Internal.createIndex(DSL.name("idx_import_jobs_started"), ImportJobs.IMPORT_JOBS, arrayOf(ImportJobs.IMPORT_JOBS.STARTED_AT.desc()), false)
val IDX_IMPORT_JOBS_STATUS: Index = Internal.createIndex(DSL.name("idx_import_jobs_status"), ImportJobs.IMPORT_JOBS, arrayOf(ImportJobs.IMPORT_JOBS.STATUS), false)
val IDX_IMPORT_JOBS_TYPE: Index = Internal.createIndex(DSL.name("idx_import_jobs_type"), ImportJobs.IMPORT_JOBS, arrayOf(ImportJobs.IMPORT_JOBS.JOB_TYPE), false)
val IDX_USER_COMMENTS_BOOK: Index = Internal.createIndex(DSL.name("idx_user_comments_book"), UserComments.USER_COMMENTS, arrayOf(UserComments.USER_COMMENTS.BOOK_ID), false)
val IDX_USER_COMMENTS_USER: Index = Internal.createIndex(DSL.name("idx_user_comments_user"), UserComments.USER_COMMENTS, arrayOf(UserComments.USER_COMMENTS.USER_ID), false)
