/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.interfaces


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IAuthors : Serializable {
    val id: Long?
    val firstName: String?
    val lastName: String
    val fullName: String
    val createdAt: OffsetDateTime?
}
