/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.interfaces


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IBookAuthors : Serializable {
    val bookId: Long
    val authorId: Long
}
