/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.interfaces


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IBooks : Serializable {
    val id: Long
    val title: String
    val `annotation`: String?
    val genre: String?
    val language: String?
    val seriesId: Long?
    val seriesNumber: Int?
    val filePath: String
    val archivePath: String
    val fileSize: Long?
    val dateAdded: OffsetDateTime
    val coverImage: ByteArray?
    val createdAt: OffsetDateTime?
}
