/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.interfaces


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IDownloads : Serializable {
    val id: Long?
    val userId: Long
    val bookId: Long
    val format: String
    val createdAt: OffsetDateTime?
}
