/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.interfaces


import io.heapy.kotbusta.jooq.enums.JobStatusEnum
import io.heapy.kotbusta.jooq.enums.JobTypeEnum

import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IImportJobs : Serializable {
    val id: Long?
    val jobType: JobTypeEnum
    val status: JobStatusEnum
    val progress: String?
    val inpFilesProcessed: Int?
    val booksAdded: Int?
    val booksUpdated: Int?
    val booksDeleted: Int?
    val coversAdded: Int?
    val bookErrors: Int?
    val coverErrors: Int?
    val errorMessage: String?
    val startedAt: OffsetDateTime?
    val completedAt: OffsetDateTime?
    val createdAt: OffsetDateTime?
}
