/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.interfaces


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IUsers : Serializable {
    val id: Long?
    val googleId: String
    val email: String
    val name: String
    val avatarUrl: String?
    val createdAt: OffsetDateTime?
    val updatedAt: OffsetDateTime?
}
