/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.pojos


import io.heapy.kotbusta.jooq.tables.interfaces.IAuthors

import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Authors(
    override val id: Long? = null,
    override val firstName: String? = null,
    override val lastName: String,
    override val fullName: String,
    override val createdAt: OffsetDateTime? = null
): IAuthors {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Authors = other as Authors
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.firstName == null) {
            if (o.firstName != null)
                return false
        }
        else if (this.firstName != o.firstName)
            return false
        if (this.lastName != o.lastName)
            return false
        if (this.fullName != o.fullName)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.firstName == null) 0 else this.firstName.hashCode())
        result = prime * result + this.lastName.hashCode()
        result = prime * result + this.fullName.hashCode()
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Authors (")

        sb.append(id)
        sb.append(", ").append(firstName)
        sb.append(", ").append(lastName)
        sb.append(", ").append(fullName)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
