/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.pojos


import io.heapy.kotbusta.jooq.tables.interfaces.IBookAuthors


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class BookAuthors(
    override val bookId: Long,
    override val authorId: Long
): IBookAuthors {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: BookAuthors = other as BookAuthors
        if (this.bookId != o.bookId)
            return false
        if (this.authorId != o.authorId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.bookId.hashCode()
        result = prime * result + this.authorId.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("BookAuthors (")

        sb.append(bookId)
        sb.append(", ").append(authorId)

        sb.append(")")
        return sb.toString()
    }
}
