/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.pojos


import io.heapy.kotbusta.jooq.tables.interfaces.ISeries

import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Series(
    override val id: Long? = null,
    override val name: String,
    override val createdAt: OffsetDateTime? = null
): ISeries {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Series = other as Series
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.name != o.name)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.name.hashCode()
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Series (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
