/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq.tables.pojos


import io.heapy.kotbusta.jooq.tables.interfaces.IUsers

import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Users(
    override val id: Long? = null,
    override val googleId: String,
    override val email: String,
    override val name: String,
    override val avatarUrl: String? = null,
    override val createdAt: OffsetDateTime? = null,
    override val updatedAt: OffsetDateTime? = null
): IUsers {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Users = other as Users
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.googleId != o.googleId)
            return false
        if (this.email != o.email)
            return false
        if (this.name != o.name)
            return false
        if (this.avatarUrl == null) {
            if (o.avatarUrl != null)
                return false
        }
        else if (this.avatarUrl != o.avatarUrl)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt == null) {
            if (o.updatedAt != null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.googleId.hashCode()
        result = prime * result + this.email.hashCode()
        result = prime * result + this.name.hashCode()
        result = prime * result + (if (this.avatarUrl == null) 0 else this.avatarUrl.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt == null) 0 else this.updatedAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Users (")

        sb.append(id)
        sb.append(", ").append(googleId)
        sb.append(", ").append(email)
        sb.append(", ").append(name)
        sb.append(", ").append(avatarUrl)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)

        sb.append(")")
        return sb.toString()
    }
}
