name: "Build Kotbusta Docker"

permissions:
  contents: read

on:
  - push
  - pull_request

jobs:
  build:
    name: "Build Application"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "corretto"
      - run: ./gradlew distTar
      - uses: actions/upload-artifact@v5
        with:
          name: "Kotlin Application"
          path: "build/distributions/kotbusta.tar"
          retention-days: 1
  build-and-push-image:
    name: "Build Docker Image"
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    needs: build
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          name: "Kotlin Application"
          path: "build/distributions/"
      - name: "Untar files"
        run: mkdir -p build/install && tar -xvf build/distributions/kotbusta.tar -C $_
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password:  ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            ghcr.io/heapy/kotbusta:main
            ghcr.io/heapy/kotbusta:${{ github.sha }}
          labels: |
            org.opencontainers.image.title=Kotbusta
            org.opencontainers.image.description=Digital library for Flibusta archives
            org.opencontainers.image.source=https://github.com/Heapy/kotbusta
