/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbusta.jooq


import io.heapy.kotbusta.jooq.tables.Authors
import io.heapy.kotbusta.jooq.tables.BookAuthors
import io.heapy.kotbusta.jooq.tables.Books
import io.heapy.kotbusta.jooq.tables.Downloads
import io.heapy.kotbusta.jooq.tables.ImportJobs
import io.heapy.kotbusta.jooq.tables.KindleDevices
import io.heapy.kotbusta.jooq.tables.KindleSendEvents
import io.heapy.kotbusta.jooq.tables.KindleSendQueue
import io.heapy.kotbusta.jooq.tables.Series
import io.heapy.kotbusta.jooq.tables.UserComments
import io.heapy.kotbusta.jooq.tables.UserNotes
import io.heapy.kotbusta.jooq.tables.UserStars
import io.heapy.kotbusta.jooq.tables.Users

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DefaultSchema : SchemaImpl(DSL.name(""), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("")) {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_SCHEMA</code>
         */
        val DEFAULT_SCHEMA: DefaultSchema = DefaultSchema()
    }

    /**
     * The table <code>AUTHORS</code>.
     */
    val AUTHORS: Authors get() = Authors.AUTHORS

    /**
     * The table <code>BOOK_AUTHORS</code>.
     */
    val BOOK_AUTHORS: BookAuthors get() = BookAuthors.BOOK_AUTHORS

    /**
     * The table <code>BOOKS</code>.
     */
    val BOOKS: Books get() = Books.BOOKS

    /**
     * The table <code>DOWNLOADS</code>.
     */
    val DOWNLOADS: Downloads get() = Downloads.DOWNLOADS

    /**
     * The table <code>IMPORT_JOBS</code>.
     */
    val IMPORT_JOBS: ImportJobs get() = ImportJobs.IMPORT_JOBS

    /**
     * The table <code>KINDLE_DEVICES</code>.
     */
    val KINDLE_DEVICES: KindleDevices get() = KindleDevices.KINDLE_DEVICES

    /**
     * The table <code>KINDLE_SEND_EVENTS</code>.
     */
    val KINDLE_SEND_EVENTS: KindleSendEvents get() = KindleSendEvents.KINDLE_SEND_EVENTS

    /**
     * The table <code>KINDLE_SEND_QUEUE</code>.
     */
    val KINDLE_SEND_QUEUE: KindleSendQueue get() = KindleSendQueue.KINDLE_SEND_QUEUE

    /**
     * The table <code>SERIES</code>.
     */
    val SERIES: Series get() = Series.SERIES

    /**
     * The table <code>USER_COMMENTS</code>.
     */
    val USER_COMMENTS: UserComments get() = UserComments.USER_COMMENTS

    /**
     * The table <code>USER_NOTES</code>.
     */
    val USER_NOTES: UserNotes get() = UserNotes.USER_NOTES

    /**
     * The table <code>USER_STARS</code>.
     */
    val USER_STARS: UserStars get() = UserStars.USER_STARS

    /**
     * The table <code>USERS</code>.
     */
    val USERS: Users get() = Users.USERS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Authors.AUTHORS,
        BookAuthors.BOOK_AUTHORS,
        Books.BOOKS,
        Downloads.DOWNLOADS,
        ImportJobs.IMPORT_JOBS,
        KindleDevices.KINDLE_DEVICES,
        KindleSendEvents.KINDLE_SEND_EVENTS,
        KindleSendQueue.KINDLE_SEND_QUEUE,
        Series.SERIES,
        UserComments.USER_COMMENTS,
        UserNotes.USER_NOTES,
        UserStars.USER_STARS,
        Users.USERS
    )
}
